### ISSUE TITLE
Why role=presentation is ignored due to a global ARIA property?

### ISSUE THREAD

**Issue by JAWS-test** [w3c/aria#1042]
https://rawgit.com/w3c/aria/master/#presentation

I don't understand why global ARIA attributes cause role=presentation to be ignored. While I can't think of any meaningful reason for this, there are 4 reasons against it:
* A role has a higher relevance than an attribute, so role=presentation should not be overcome by e.g. aria-haspopup
* The rule has no equivalent in HTML (e.g. title attribute does not override role=presentation)
* Rule is hardly supported by assistive technology (mobile devices could still be tested to support this statement): not supperted by JAWS with Chrome, IE 11 and Firefox (https://github.com/FreedomScientific/VFO-standards-support/issues/256), not supported by NVDA with IE 11 and Firefox; only supported by NVDA with Chrome.
* It is strange that the attribute, because of which role=presentation is ignored, is not output by the screenreader at the end, because the elements do not get the focus and are only reached linearly. For example, the aria-haspopup in my example is never output by any screenreader-browser combination.

In addition, the rule does not describe what would be correct in the following cases:
* implicit role=presentation (is this a heading inside a button?): 
```
<button><h2 aria-haspopup=true>h2</h2></button>
```
* inherited role=presentation (is this a listitem without a list):  
```
<ul role=presentation><li aria-haspopup=true>listitem</li></ul>
```
This applies analogously to the rule that role=presentation should be ignored if the element is focusable (https://github.com/w3c/aria/issues/1041).

**Comment by scottaohara** [comment]
The section [Presentational Roles Conflict Resolution](https://rawgit.com/w3c/aria/master/#conflict_resolution_presentation_none) does go into detail to explain this, ending with the following that sums up the reasoning quite well IMO:
> If an element with a role of presentation is focusable, or otherwise interactive, user agents MUST ignore the normal effect of the role and expose the element with implicit native semantics, in order to ensure that the element is both understandable and operable.

So global attributes should overwrite the presentation/none role so as to ensure attributes that communicate special semantics and functionality are not obscured by what may likely be an author error in setting an element to be both presentational while also attempting to communicate information.

>The rule has no equivalent in HTML (e.g. title attribute does not override role=presentation)

That is true, and to be fair, possibly something to think more on.  However, being a focusable element is supposed to override role presentation, and being that focusable elements are typically (but not always) the elements that best expose the value of a title attribute.  I know you've written another issue about role presentation and focusable elements.  If you are finding issues with that rule being followed then those are bugs with the assistive technology or browsers.  

Regarding your examples, they would both produce HTML that would be invalid, so it seems counter productive to spend time validating examples that are invalid to begin with.  E.g. a heading within a button is invalid.  A list item without a parent list element is invalid. 

That said, doing a quick test of the following:
```html
<main aria-label="named" role=presentation>should expose as main</main>
<header role=presentation aria-haspopup=true>should expose as banner (if scoped to body)</header>
<aside role=presentation aria-haspopup=true>should expose as complementary</aside>
<button role=presentation>should expose as button</button>
```
All these tests pass as FIrefox exposes the proper semantics (ignoring presentation) to the accessibility tree.

However, if testing with Chrome only the button is correctly exposed, resulting in NVDA and JAWS not finding the landmarks. This is because *Chrome is not ignoring the presentation role*.  And this is an important distinction that you should be aware of, as some of the issues you have been filing are not bugs with the specification, or even with JAWS, but rather gaps in browser implementation.
