### ISSUE TITLE
Let web developers signal their "DPAD mechanics"

### ISSUE THREAD

**Issue by hugoholgersson** [w3c/aria#1049]
# Background
When users browse the web on their TV, the remote's directional pad, "the DPAD" (usually 4 arrow keys), is often the only input device available.

Most web apps have custom JS to move focus upon DPAD (or, more generically, arrow key) input. However, Chromium's built-in "focus moving logic", [Spatial Navigation](https://drafts.csswg.org/css-nav-1/), has become better the last few years so app authors might now choose to offload their JS' "focus movement"-logic to the browser.

# General problem
A browser cannot know if a web app has either:
1. Built-in JS logic for directional focus movements (YouTube TV and others).
2. No built-in JS logic that moves focus (probably not a TV app).
3. No built-in JS logic that moves focus but works well with Spatial Navigation.

# Accessibility problem
Some screen readers, such as TalkBack on Android TV, walk web pages *sequentially*, **even if the app has its own DPAD-logic in JavaScript**.

When TalkBack reads a TV web app with built-in DPAD support, TalkBack moves focus sequentially (think Tab/Shift+Tab) even though the web app has its own DPAD-logic. => The web app's UX degrades from 2D to 1D directional navigation only because the user enabled her screen reader!

# Suggestion
An attribute, for now let's call it `dpad`, that gives the browser (and screen readers) a hint about how the author expects focus movement/highlighting to happen:

## Example:

```
(1) <body dpad="js">       <!-- This app moves and highlights focus in its own ways. -->
(2) <body dpad="default">  <!-- The browser (or a screen reader) _may_ move and highlight focus. -->
(3) <body dpad="browser">  <!-- The app _requests_ Spatial Navigation to move and highlight focus. -->
```

Here the attribute indicates how navigation is supposed to work within the document. 
Most TV apps use one strategy for the entire app so the primary (or only?) use case would be to put the attribute on the document `<body>`.

In all cases, a screen reader may still emphasize `activeElement` the way TalkBack does with its green rectangle *above* the web content. A rectangle on top of the content, rendered outside the browser, is fine because it will not conflict with the web page's `:focus` CSS.

## Follow-up
`<body dpad="..">` is the primary use case but, as a follow-up, `<div dpad="..">` could be a hook for web developers (or custom element developers) to control focus management within widgets (DOM sub trees).

## Possible implementation
When `activeElement` is within a `dpad="js" / "browser"` sub tree, the browser could expose a one-node accessibility tree that only consists of `activeElement`. This would force screen readers to only speak about `activeElement`, keep it from navigating elsewhere and, instead, let the DPAD/arrow key events through to the web page.

**Comment by jnurthen** [comment]
Can you explain how this is different to role=application?

Note - we really try not to encourage use of role=application as it makes it much more difficult to use many of the ways that screen reader users use to navigate pages. 
From what I understand of this request it sounds like you want  a more locked down version of role application. My personal opinion is that I think this would be resisted by users due to the massive potential for misuse.

**Comment by hugoholgersson** [comment]
Thanks. I didn't know of role=application. I guess TV apps like YouTube TV should use this role?

> Can you explain how this is different to role=application?

Yeah. What I request is a way for authors to not only hint "we're handling focus movements on our own" (role=application) but also 1) hint _how_ focus movements are handled so 2) for dpad="browser", actually trigger the browser to go into Spatial Navigation mode. 1) and 2) are implementation details the screen reader doesn't need to know about.

> From what I understand of this request it sounds like you want a more locked down version of role application.

role=application sounds like a good thing. I don't want to change it. I think my suggestion, since it's not only describing the content but also potentially triggers Spatial Navigation, makes more sense in another spec. A screen reader doesn't need to know _how_ focus movements are implemented by the app.

> Note - we really try not to encourage use of role=application as it makes it much more difficult to use many of the ways that screen reader users use to navigate pages.

Understood. role=application means the author must take full responsibility for focus movements.

Imagine `dpad` becomes standardized elsewhere... If `role` is not already set, then I guess `dpad` should give `role` an implicit value:

| dpad=  |  role=   | 
|---|---|
|  js  | application  |
|  default  | _unchanged_ |
| browser  | application  |

Does that make sense? (There's no new, locked down, role here so the risk of misuse is the same.)

**Comment by pkra** [comment]
>  A screen reader doesn't need to know how focus movements are implemented by the app.

I think that's not the case. 

The following may be too far apart from what @hugoholgersson has in mind but let me write it down and if it turns out to be off-topic, I'll hide the comment.

I'm quite interested in the topic of "something less extensive than role=application". That is, ways to provide AT with more information about the content structure and preferred navigation as intended by an author while keeping AT's ability to override where needed. 

An existing example are table walkers provided by most screenreaders. They allow two dimensional navigation as opposed to the linear reading modes and positional information, purely from HTML markup (in particular, no JS). 

An example of a role that I think could become or lead to another example would be role=tree. That is, AT could provide treewalkers much like it provides table walkers (e.g., depth-first, breadth first). 

I like role=tree because it is already an example of slowly reducing authoring complexity: setting active-descendant vs moving tabindex, creating aria-setsize, aria-posinset, aria-level vs browsers calculating those automatically. In the light of this history, it does not seem too far fetched to work across the stack to ensure AT can provide basic tree navigation while allowing authors to nevertheless do fancier (optional) navigation via JS (e.g., cyclical navigation on a tree level can be very helpful in SVG content).

**Comment by pkra** [comment]
We discussed this issue on the ARIA WG call on Sept 26. 

It's not clear to the WG how this issue relates to ARIA. The problem appears to be primarily about how Assisitive Technology focus management interacts with the CSS spatial navigation spec. 

We would suggest to perhaps start a discussion on the spatial navigation end so as to identify issues that relate to accessibility in general and ARIA (or related) specs in particular. In fact, there already has been some discussion around (the trouble of) focus managment, cf. https://github.com/w3c/csswg-drafts/issues/3379 which seems like a good place to continue fleshing out this problem.
