### ISSUE TITLE
heading with aria-level > 6

### ISSUE THREAD

**Issue by JAWS-test** [w3c/aria#1050]
I suggest that https://w3c.github.io/aria/#heading explicitly mentions that aria-level, unlike HTML headings, can be greater than 6.

**Comment by sahilempire** [comment]
I want to work on this issue, **please assign me**.

Thank you.

**Comment by sahilempire** [comment]
Hello @jnurthen ,

I am **new and a quite beginne**r in the **world of Open Source**, so **please help me** through and **please tell me what exactly I have to do**.

Thanking you

**Comment by johnfoliot** [comment]
I don't have too much skin in the game here, but I question whether allowing aria-level to exceed "6" is a good idea or not. 

My understanding with a lot of the aria attributes is/was to develop parity with host languages (here HTML), and in HTML, the heading levels go from 1 to 6. Experience suggests however that under most circumstances, headings beyond level 'h5' are exceedingly rare, and I question any real value in allowing aria-level to fork from the default values previously determined in HTML, and supported by AT for more than 2 decades. (Do we have any assurance or indication that assistive technology would support a level 7, 8, 9, or 10?) 

If anything, rather than making an edit to role=heading, I'd seek to add [clarification to aria-level](https://w3c.github.io/aria/#aria-level) and implement a max value (of 6).

My $0.02 from an old punter.

**Comment by sahilempire** [comment]
Hello, @johnfoliot ,

You are absolutely correct, because as a Web Developer, I am understand the concept of this heading and all, so I don't think so, that we have to add more heading levels.

So please tell me now what next I have to do, as I really want to contribute in W3C.

Thanking You.

**Comment by jnurthen** [comment]
@JAWS-test do you have a test page which shows the level of support for heading levels > 6?

**Comment by JAWS-test** [comment]
@jnurthen https://codepen.io/jaws-test/pen/bGBOgQX

###Test results

* JAWS + Edge, IE 11, Chrome, Firefox: 1-6 as level 1-6, all other as level 2, fractional numbers are rounded down
* NVDA + Edge, Chrome: 1-9 as level 1-9, all other as level 2, fractional numbers are rounded down
* NVDA + IE 11: 1-1000000 as level 1-1000000, without level and 0 as heading without any level, fractional numbers are rounded down
* NVDA + Firefox: 1-1000000 as level 1-1000000, without level and 0 as level 2, fractional numbers are rounded down
