### ISSUE TITLE
AriaAttributes cannot be nullable

### ISSUE THREAD

**Issue by annevk** [w3c/aria#1058]
At least as currently defined it seems to use HTML's reflect concept and that only works for normal strings, not nullable strings.

**Comment by bzbarsky** [comment]
Relatedly, `ariaActiveDescendantElement` is claimed to reflect `aria-activedescendant`, but reflection is not defined at all for things that return `Element`...

**Comment by bzbarsky** [comment]
Looks like Chrome's IDL allows [Reflect] in all sorts of cases that are not supported and just silently ignores it sometimes or something...

Anyway, the nullable DOMString case lands in https://cs.chromium.org/chromium/src/third_party/blink/renderer/bindings/core/v8/generated_code_helper.cc?l=145-159&rcl=0f7e56f37186facc1d9c9edfccb279892b2beb59 which I believe ends up doing the bit at https://cs.chromium.org/chromium/src/third_party/blink/renderer/bindings/core/v8/v8_string_resource.h?l=179-183&rcl=c109404f6df33717fecf49aabb495f2f2e4059aa to create a "null string" to the attribute setter, but the setter then ends up treating that just like it would an empty string.

That's on set.  On get, I _think_ empty string is returned if the attr is not present, but I'm not 100% sure from reading the code, and I don't know how to enable this bit in Chrome to test.

**Comment by domenic** [comment]
> Relatedly, ariaActiveDescendantElement is claimed to reflect aria-activedescendant, but reflection is not defined at all for things that return Element...

This is in progress in https://github.com/whatwg/html/pull/3917 but there are still open design discussions; see https://github.com/whatwg/html/issues/3515 and https://github.com/whatwg/html/issues/4925. (Those open design questions are why we're holding back on shipping.)

Nullable string reflection is defined for enumerated attributes, but I'm not sure the ARIA attributes in question are enumerated, or even if they are, whether they have properly-defined missing value defaults. We'll look in to that further. /cc @rakina @alice. (If either of you knows Meredith's GitHub handle please add her too.)

**Comment by domenic** [comment]
At a quick look, it seems like a reasonable fix here would be some glue at the top of the ARIA spec, which says something like "when we have a table enumerating the values for an attribute, then that attribute is an enumerated attribute. When we notate one of the values as (default), then that value is the missing value default and invalid value default for the attribute."

**Comment by alice** [comment]
(Meredith's GitHub handle is @dot-miniscule)

**Comment by alice** [comment]
Now that I'm a bit more awake: @domenic's suggestion in https://github.com/w3c/aria/issues/1058#issuecomment-548544675 seems reasonable to me. 

Do we need to worry about missing value defaults for string-type attributes like `aria-label`?

**Comment by domenic** [comment]
> Do we need to worry about missing value defaults for string-type attributes like aria-label?

Nope, only enumerated attributes. Which I guess would correspond to true/false, tristate, true/false/undefined, and token types in http://w3c.github.io/aria/#propcharacteristic_value.

token list is an interesting one. It seems like maybe `aria-dropeffect=""` and `role=""` should be exposed as DOMTokenLists? For those you'd want to do

```
[SameObject, PutForwards=value] readonly attribute DOMTokenList role;
```

**Comment by carmacleod** [comment]
I don't know if this is relevant here, but in case it is, note that `aria-activedescendant` can have a null (empty string) value and it's not an enumerated attribute. Authors do this all the time in the context of a combobox, i.e. when the combobox is closed, code just nulls activedescendant instead of removing it.

The following paragraph was added to the [State and Property Attribute Processing section](https://w3c.github.io/aria/#state_property_processing) in the ARIA spec in https://github.com/w3c/aria/issues/501 in order to accomodate this:

> Sometimes states and properties are present in the DOM but have a zero-length string ("") as their value. Authors MAY specify a zero-length string ("") for any supported (but not required) state or property. User agents SHOULD treat state and property attributes with a value of "" the same as they treat an absent attribute. For supported states and properties, this corresponds to the default value, but if it is a required attribute, it signals an author error, and the implicit value for the role is used.

**Comment by sinabahram** [comment]
I think there are three options.

 

#1: We make a new meta called alt_original or something like that, and put it in there. If it already has that meta, we override its value.

 

#2: We override the alt in Coyote.

 

#3: We add another alt (there can be of course many, so nothing wrong with this in Coyote land).

 

I’m not a huge fan of #3 because it seems like then we have to figure out a multi-alt situation for things as a normal case instead of a case where we are intentionally using multiple alts e.g. in the case of alts in different languages or for different reasons.

 

#1 and #2 are kind of equal  to me. The first one offers the ability to always know/track the first original alt at the time of resource creation, which seems useful. #2 is nice and standard e.g. you had an alt for this thing, and I updated it for you, but the downside is what if someone installs the plugin, uses it, and then uninstalls it. Then they go install it again, but in the mean-time, some folks have done something silly with alt text e.g. put the word “decorative” in (I literally just saw this on a site), so then Coyote goes and overrides the alt it knows with “decorative”, and we have a lossy situation.

 

So, with all that said, my thinking is leading me to putting this in alt_original, and if there is no alt then serving alt_original so a resource doesn’t become less accessible by getting entered into Coyote.

 

Flip, if you feel the serving of alt_original if no alt is too complex/complicated/error-prone, then I vote for overriding alt.

 

Thoughts?

**Comment by sinabahram** [comment]
Ignore my comment on this thread if you got it before I deleted it. Email client issue. My appologies *smile*.

**Comment by annevk** [comment]
@carmacleod the empty string is not a null value. Null in this thread refers to the IDL null type signified by a question mark in IDL blocks. It's distinct from the empty string and in the JavaScript bindings you would get `null` (and not `""`).
