### ISSUE TITLE
Something confuses me about TABS and aria-expanded / aria-selected

### ISSUE THREAD

**Issue by LaurenceRLewis** [w3c/aria#1091]
The ARIA Practices Guide 1.1 and 1.2 have eliminated aria-expanded and use aria-selected to indicate the expanded (active) tabpanel.

This makes no sense to me.

The way I imagine these should work:

When the tabpanel is expanded **aria-expanded** is set to **true** on the corrisponding **role=tab** and all other **role=tab** have **aria-expanded** set to **false**.

All **role=tab** include **aria-selected**. When focus is on the **role=tab, aria-selected** is set to **true**, regardless of whether the tabpanel is expanded. So moving focus to a tab using the left right arrow key causes **aria-selected true** to apply to the focused tab.

aria-selected (state) Indicates the current "selected" state. Is the selected state whan an element has focus? And the expanded state when tabpanel content is visible?

A lot of my confusion comes from the description for aria-selected:

`Any explicit assignment of aria-selected takes precedence over the implicit selection based on focus. If no DOM element in the widget is explicitly marked as selected, assistive technologies MAY convey implicit selection which follows the keyboard focus of the managed focus widget. If any DOM element in the widget is explicitly marked as selected, the user agent MUST NOT convey implicit selection for the widget.`

Any explicit assignment of aria-selected takes precedence over the implicit selection based on focus. Does this mean that if aria-selected is set by an onClick event (on an expanded tabpanel) that even if focus is moved to a new tab, aria-selected MUST not be set to true for the focussed tab? As described above, when I move focus to a different tab I expected it to be announced as selected true.

Perhaps it is just me that is confused how aria-selected is, or should be, interpreted.

**Comment by JAWS-test** [comment]
I understand it that way:
* `aria-selected` has nothing to do with the focus, but indicates which element was selected (e.g. which tab is currently displayed)
* There is no ARIA role for the current focus.
* However, if the focus in a widget always matches the selected element (as with the HTML element `select` without multiple selection or as with [Example of Tabs with Automatic Activation](https://w3c.github.io/aria-practices/examples/tabs/tabs-1/tabs.html),) `aria-selected` can theoretically be omitted, because AT can then automatically output the focused element as selected. However, this is not recommended, because e.g. a screenreader cannot recognize the selected element when reading with the arrow keys (in my opinion this hint is still missing in the specification and should be added at `aria-selected`).
* `aria-expanded` can still be used with tabs if several tabs can be open at the same time:

>  For a multi-selectable tablist, authors SHOULD ensure that the tab for each visible tabpanel has the aria-expanded attribute set to true, and that the tabs associated with the remaining hidden tabpanel elements have their aria-expanded attributes set to false. (https://w3c.github.io/aria/#tab)

I propose to add in the specification that every ARIA role that allows `aria-selected` and that can be operated should always be tagged with `aria-selected`.

**Comment by LaurenceRLewis** [comment]
@JAWS-test. That makes sense. Thank you. 

It does seem, to me at least, that there is some crossover between aria-expanded and aria-selected. However, I understand now how these are interpreted. 

Visually moving between tabs using the arrow keys there is generally some indicator of the tab focused. This is why I assumed incorrectly that aria-selected had the same purpose.
