### ISSUE TITLE
aria-roledescription should not duplicate the implicit or explicit role

### ISSUE THREAD

**Issue by pkra** [w3c/aria#1131]
From a discussion on the WG call on 2019/12/05 (though [it wasn't minuted](https://www.w3.org/2019/12/05-aria-minutes.html)).

The spec currently reads

>  When using aria-roledescription, authors SHOULD also ensure that:
>
>    1. The element to which aria-roledescription is applied has a valid WAI-ARIA role or has an implicit WAI-ARIA role semantic.
    2. The value of aria-roledescription is not empty or does not contain only whitespace characters.

It seems useful to add that a role description should not duplicate the (implicit or explicit) role of the element since that can negatively impact users, e.g., Braille translation could become more verbose.

**Comment by pkra** [comment]
I'm wondering what "duplicate" should effectively mean, e.g., "img" vs "image" vs "visualization". This might be more fitting for authoring guidelines than spec text.

**Comment by JAWS-test** [comment]
> It seems useful to add that a role description should not duplicate the (implicit or explicit) role of the element since that can negatively impact users, e.g., Braille translation could become more verbose.

I would say the opposite: it makes sense if aria-roledescription repeats the explicit or implicit role or uses a similar role name so that the role becomes clear for AT users. Reason: with aria-roledescription the original role is NOT output anymore.

**Comment by stes-acc** [comment]
I am a bit torn here, if roledescription is giving extra semantics for some roles (like setting it on a special kind of listitem role) I am OK with not mentioning the role name, whereas for button or link this would be way more critical. Therefore I do NOT recommend  using roledescription on form elements or links/buttons etc.

So we have basically 3 levels

Alllowed not giving role name as part of roledescription
role = application
...

Debatable
list, listitem
...

Not allowed (since superfluous)
Button

**Comment by sinabahram** [comment]
I am not at all a fan of restricting roledescription on form elements or not allowing it to fully override what is spoken for role.

A simple example is:

<button aria-roledescription="Light Switch" aria-label="Living Room" aria-pressed="false">

</button>

Note, Jaws doesn't read the above correctly, but NVDA does a beautiful job saying "living room light switch not pressed".

That is a pleasant and lovely experience. I do not wish to prevent it.

**Comment by JAWS-test** [comment]
@sinabahram: The JAWS output of your example is not that bad. aria-pressed=true is output correctly. aria-pressed=false is output at least for tab navigation with a hint that points to a switch

**Comment by sinabahram** [comment]
@JAWS-test  let's put it this way. It is broken, full stop. It needs to be fixed, and how NVDA says it in focus mode is the typical/expected way, even for Jaws, in this specific case (obviously that's not always true). And, to be fair, NVDA has a bug too because NVDA says, in browse mode, "light switch living room not pressed", which I find suboptimal, but I understand that this is a much larger issue in NvDA land and I think there's already some issues around it.

**Comment by JAWS-test** [comment]
@sinabahram I don't think the screen reader can be expected to suddenly output more information with aria-roledescription than without. Therefore, I think the JAWS output is correct. The example rather shows the limitations of aria-roledescription. If you see it differently, it would be wise to create tickets in JAWS and NVDA to fix the errors.

**Comment by sinabahram** [comment]
@JAWS-test , I really don't think you are experiencing the same as I am here. This has now been the case a few times across repositories where your results have not matched multiple other Jaws users. I don't know if it is a setup difference, but over here, and I've verified on other configs, Jaws does not read out that control as a control. I'm not speaking of tabbing to it, but when using it with the virtual cursor. Yes, absolutely Jaws can be expected to announce the state of a control. It does so with every other  control it works with, so your claim makes no sense to me e.g. button, expanded/collapsed, summary/details (same thing), checkboxes (checked/unchecked), radio buttons (same thing), etc.

Take the snippet I provided, run it in Chrome/Firefox, and play with it in browse mode and insert mode with NVDA, and then do the same with Jaws (virtual/forms). The bugs are quite obvious in Jaws in that situation. It would be good not to give the sense that Jaws is working well when it is not. False positives are really bad.

**Comment by JAWS-test** [comment]
> Jaws does not read out that control as a control

Like NVDA and as required by the specification, JAWS outputs the value in aria-roledescription both with the virtual cursor and in forms mode. I'm sorry, I really don't understand what the problem is. I suspect we both have the same output in JAWS, but a different understanding of what JAWS should output

**Comment by sinabahram** [comment]
@JAWS-test  it says "living room light switch", not "living room light switch not pressed". This is pretty critical because the state is not being conveyed. NVDA does not have this issue.

**Comment by JAWS-test** [comment]
@sinabahram: The status is only transmitted if aria-pressed=true is present. However, it is standard in JAWS that the false status is not reported for certain ARIA attributes (such as aria-pressed, aria-selected). Instead, aria-pressed changes the role from button to switch. But if I overwrite the role with aria-roledescription, it should be done in a way that the role is still perceived correctly. This was the intention of my comment https://github.com/w3c/aria/issues/1131#issuecomment-565423968

**Comment by sinabahram** [comment]
@JAWS-test , Jaws should say "living room light switch not pressed". It doesn't do so, and I believe this to be a mistake. Buttons have implicit semantics, but there's no clue that "living room light switch" is a "light switch", until you navigate by button/form-element or start tabbing, so if roledescription is present, Jaws should say the value of pressed=false or true, since it is no longer a shortcut or abbreviation choice that they have made on button, even though I also disagree that a button with pressed=false doesn't read. There's then no way to tell it from a button without aria-pressed semantics. This would be the exact same as leaving off aria-expanded when it is set to false, which is uninformative and frankly simply wrong, so I'm not sure what else I can say on this topic, but I think NVDA has the exact correct behavior here.

**Comment by stes-acc** [comment]
This discussion belongs more in the APG Github space. But ARIA spec itself is maybe not verbose enough about correct and incorrect use cases. As I said, we should discuss correct usage of aria-roledescription with precedence.

**Comment by mcking65** [comment]
@pkra 

Since we now have aria-brailleroledescription in the spec with appropriate authoring requirements, is the ARIA spec aspect of this issue now resolved? Can we close this?

BTW, he APG issue for this is w3c/aria-practices#651.

**Comment by pkra** [comment]
> Since we now have aria-brailleroledescription in the spec with appropriate authoring requirements, is the ARIA spec aspect of this issue now resolved? Can we close this?

@mcking65 I'm ok with closing this in favor of an APG issue. An authoring SHOULD NOT is a fairly weak requirement anyway. 

(For other people's context, this issue was not about the braille properties themselves. I filed it after a call where we had finalized a similar phrasing for braille role description.)

**Comment by pkra** [comment]
Closing this for now -- if anyone feels more strongly about it, please feel free to re-open.
