### ISSUE TITLE
Issues with conformance section

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/aria#1153]
Conformance section is in section 3 of the document. This is the same as for ARIA 1.1, but the difference with ARIA 1.2 is that in ARIA 1.2, section 2 already has conformance requirements. It would be better to have the conformance section either before all conformance requirements, or at the end of the document.

Second point, there are quite a few places in the document where words from BCP 14 are used where they should not have been. For example:

> source: https://www.w3.org/TR/wai-aria-1.2/#authoring_testing
> The accessibility of interactive content cannot be confirmed by static checks alone. Developers of interactive content should test for device-independent access to widgets and applications, and should verify accessibility API access to all content and changes during user interaction.

> source: https://www.w3.org/TR/wai-aria-1.2/#managingfocus_useragents
> Implement the host language method for keyboard navigation so that widgets that support aria-activedescendant may be included in the tab order.

> source: https://www.w3.org/TR/wai-aria-1.2/#math
> At the time of this writing, some mainstream browsers do not support MathML natively, and must be retrofit using a JavaScript polyfill library. When authoring math content, use native MathML wherever possible, and test thoroughly. Use a polyfill library or provide a fallback image with a text alternative approximation if necessary.

**Comment by carmacleod** [comment]
Hi @WilcoFiers !
> section 2 already has conformance requirements

Actually, there are no conformance requirements in  [section 2](https://w3c.github.io/aria/#usage). The first sentence of that section is:
> _This section is non-normative._

The ARIA spec follows [BCP 14](https://tools.ietf.org/html/bcp14). If you look for the word "lowercase", you will find the following:
> ... only UPPERCASE usage of the key words have the defined special meanings.

That said, the ARIA Working Group acknowledges that the HTML spec has [decided to use lowercase keywords](https://github.com/w3c/aria/pull/1127#issuecomment-567394042) for readability. The ARIA WG further acknowledges that authors coming from the HTML spec to the ARIA spec could find lowercase "may", "should", etc confusing in non-normative content.

There is an [open pull request](https://github.com/w3c/aria/pull/1127) to change any potentially confusing non-normative uses of "may", "should", etc, to non-normative words like "can", "might", etc. 

We plan to merge that PR after a sufficient number of reviewers have reviewed and approved it.

So I'll close this issue because it is covered in PR #1127.

**Comment by jnurthen** [comment]
I don't think section 2 should be non-normative. Adding this to a future meeting agenda.

**Comment by jnurthen** [comment]
I propose moving section 2 to after "Important Terms" (currently section 4)

**Comment by jnurthen** [comment]
.....and also investigate whether the current section 2 should (or not) be normative and, if needed, change language to match the decision.

**Comment by carmacleod** [comment]
> I don't think section 2 should be non-normative.
> I propose moving section 2 to after "Important Terms" (currently section 4)
> ...and also investigate whether the current section 2 should (or not) be normative...

Interesting. Ok, looking more closely, I see that subsections **2.1** and **2.2** are still mostly non-normative. They introduce roles, states and properties.

One paragraph of **2.1** is normative (the part starting with "User agents MUST" and including the list of steps), and all of **2.3** is normative.

We could either move these subsections somewhere else, or - more simply - just say that all of section 2 is normative.

Regarding where it belongs in the document... if section 2 (Using WAI-ARIA) is made normative, then it needs to go after the Conformance section, and it could even go after the Important Terms section. This pushes the "meat" of the document quite a bit later, but it gets the boilerplate stuff out of the way earlier, which is a plus.

There's also something weird going on with the "Conformance" section (currently 3). The first instance of a section with `class="normative"` must be pulling in extra content from somewhere, which is unfortunately redundant with some of the content that is already in the Conformance section.
