### ISSUE TITLE
Native captions should not need to be aria-labelled 

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/aria#1173]
The caption role has the following "SHOULD" requirement:

> Authors SHOULD set aria-labelledby on the parent figure, table, or grid to reference the element with role caption.

There should be an exception for HTML `table` and `figure` elements here, or maybe some more generic "if the host language" type of thing. In HTML, the caption becomes the accessible name of the table, same for figure / figcaption as described in [html-aam 1.0](https://www.w3.org/TR/html-aam-1.0/#table-element). Using aria-labelledby here is redundant.

**Comment by scottaohara** [comment]
I'm unsure about this one.  Naming by encapsulation was pushed to ARIA 1.3, so while the roles are getting added for ARIA 1.2, I don't know that we can bank on these naming their parent elements without a helping hand in the interim.  Maybe I'm wrong about this, so @jnurthen @joanmarie please do correct me here if need be.

Regardless, I would be more concerned with stating something like this and giving authors the impression that they could add a `div role=caption` as a child of a`table` and that wouldn't get auto-corrected by browsers.

For example:
```html
<table>
  <div role=caption>hi i'm a caption</div>
  <tr>
    <th>cell 1</th><th>cell 2</th>
  </tr>
  <tr>
    <td>content 1</td><td>content 2</td>
  </tr>
</table>
```

is corrected by browsers to:
```html
<div role=caption>hi i'm a caption</div>
<table>
  <tr>
    <th>cell 1</th><th>cell 2</th>
  </tr>
  <tr>
    <td>content 1</td><td>content 2</td>
  </tr>
</table>
```

because `div`s aren't allowed child elements of `table`.

Additionally, might this not set a precedent that we would need to call out other HTML considerations and gotchas when mixing ARIA and HTML?  For example, while `div role=listitem` can be added as a child of `ul`, you can't do the same with `div role=option` to a `select`.   I think we should err on the side of the ARIA spec indicates how to properly use ARIA.  If there are potential caveats for how ARIA could/should work with HTML, that's what we can use the ARIA in HTML specification for.

**Comment by carmacleod** [comment]
I thought (?) that @WilcoFiers meant that if the author uses an HTML caption element (which has an implied role of "caption"), in a table then they don't need to use `aria-labelledby`, so maybe we needed to add some words around that for clarity.

... However, thinking about it a bit more, if an author is using an HTML caption in an HTML table, then they don't need the ARIA spec for that. :)

So maybe I misunderstood the original issue (title is "Native captions should not need to be aria-labelled").

If I misunderstood, then +1 to @scottaohara's answer.

**Comment by jnurthen** [comment]
@WilcoFiers does this answer your question. Can we close?

**Comment by carmacleod** [comment]
The ARIA Working Group just discussed `Native captions should not need to be aria-labelled`.

<details><summary>The full IRC log of that discussion</summary>
&lt;carmacleod> github: https://github.com/w3c/aria/issues/1173<br>
&lt;carmacleod> jamesn: waiting for wilco<br>
</details>

**Comment by jnurthen** [comment]
@WilcoFiers based on no response above I am going to close
