### ISSUE TITLE
Combobox and aria-multiline

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/aria#1176]
Combobox says: 
> If an element with role combobox supports text input, authors MUST ensure that the text input has aria-multiline set to false

This is rather odd, since `aria-multiline` is not a supported role for `combobox`.

**Comment by mcking65** [comment]
@WilcoFiers, good catch. Since we made the combobox itself an input instead of a wrapper, there is no longer a textbox, which means we do not need to say anything at all about aria-multiline. This is yet one more advantage of the simplified structure.

PR #1197 removes the sentence with the normative authoring requirement.
