### ISSUE TITLE
Move section on presentation role conflicts to “Handling Author Errors”

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/aria#1211]
There is an important normative sub-section (added for ARIA 1.1) about ["Presentational Roles Conflict Resolution"](https://w3c.github.io/aria/#conflict_resolution_presentation_none), which is currently tucked away under the definition of the "presentation" role.

It should probably be moved to the new [“Handling Author Errors”](https://w3c.github.io/aria/#document-handling_author-errors) top-level section.

**Comment by cookiecrook** [comment]
No objection about the move. 

Additional editorial issue that could be handled at the same time: We've been trying to use the synonym `role="none"` in prose and examples instead of `role="presentation"` because authors have a better conceptual understanding of "no role." Authors conflated `role="presentation"` sometimes with "presentational" which many authors assume equates to `aria-hidden="true"`. This is the original reason we added the `role="none"` synonym.
