### ISSUE TITLE
double check normative and informative references for aria 1.2

### ISSUE THREAD

**Issue by scottaohara** [w3c/aria#1214]
For instance, noticed today that WAI-ARIA-PRACTICES-1.1 was listed as a normative reference.

**Comment by a11ydoer** [comment]
Michael said, it is from respec and adding exclamation point makes the rule as normative, without it, it is informative. @carmacleod will look into the issue.

**Comment by carmacleod** [comment]
`[[!doc]]` is normative
`[[doc]]` is non-normative

Also need to check version numbers, if they are in the citation, to make sure they are up to date.

**Comment by carmacleod** [comment]
@mcking65 says reference to apg in combobox has a version number

**Comment by michael-n-cooper** [comment]
On version numbers, you have the option of doing [[wai-aria-practices]] or [[wai-aria-practices-1.2]]. The first will pick the latest version (that's at Note or Rec), the second will pick that specific version. In general we use non version specific references, except for cross references with the ARIA suite where the version dependencies are more specific where we use specific versions and update them each time we start a new version number.

**Comment by jnurthen** [comment]
https://github.com/w3c/respec/wiki/ReSpec-Editor's-Guide#references

For a non-normative reference in a normative section use `[[?doc]]`

**Comment by carmacleod** [comment]
This issue is more involved than it seemed at first glance (i.e. it's about much more than just making sure APG references are non-normative). So I need to check some assumptions. Anybody who knows any answers, please chime in:

1. In the `respecConfig` json at the beginning of the doc, `accNameURLs`, `coreMappingURLs`, and `practicesURLs` are all currently at 1.1. I think they all need to be bumped up to 1.2 - correct?

2. `ariaSpecURLs` in `respecConfig` is empty - is that intentional?

3. `doRDFa: '1.1',` is [deprecated](https://github.com/w3c/respec/wiki/doRDFa-(DEPRECATED)). Shall I just ignore that for now?

4. CSS3-SELECTORS has moved on to [CSS Selectors Level 4](https://www.w3.org/TR/selectors/). (Someday, there may or may not be an actual [CSS4](https://github.com/w3c/csswg-drafts/issues/4770), but for now, we should bump up the CSS Selectors version).

5. DOM4 should just be DOM.

6. Do we want to bump DPUB-ARIA-1.0 up to DPUB-ARIA-1.1? Or maybe simply keep it version-less as [DPUB-ARIA](https://w3c.github.io/dpub-aria/)?

7. We should probably keep SVG2 for now (and not change the reference name to SVG). However, note that there's a normative [SVG2] reference and an informative [SVG] reference, which oddly pulls in a link to the latest SVG with mismatched link text for SVG 1.0. We should probably update our ref to SVG2 (keep normative?), and the [reference database](https://github.com/tobie/specref) should probably be updated to at least fix the link text. Anybody know where the [SVG2] reference is defined? I only see SVG1 in our biblio.js, and SVG10 (alias: SVG) and SVG112 (alias: SVG11) in the reference database biblio.json.

8. Do we want to update our MSAA, UI-AUTOMATION and UIA-EXPRESS links so that they are not redirected?

9. There's a reference to the previous version of the ARIA spec in the [Abstract](https://w3c.github.io/aria/#abstract) section at the beginning of the document. The reference is currently being interpreted as informative. Should I change that to normative (i.e. using `[[!doc]]`)? Or is the previous version of a spec considered to be informative after the new normative version is published?

10. @michael-n-cooper said, "In general we use non version specific references". Currently, all references to CORE-AAM, ACCNAME, and WAI-ARIA-PRACTICES contain the 1.1 version number, i.e. CORE-AAM-1.1, ACCNAME-1.1, WAI-ARIA-PRACTICES-1.1. _**I believe the version number should be deleted from ALL references to CORE-AAM, ACCNAME, and WAI-ARIA-PRACTICES in the ARIA spec**_. Please confirm, after reading the rest of this issue comment.

11. @mcking65 Please double-check and confirm that you want the WAI-ARIA-PRACTICES-1.1 reference in [combobox](https://w3c.github.io/aria/#combobox) (right before the Characteristics table) to point to the latest, i.e. WAI-ARIA-PRACTICES with no version (or do you want it to specifically point to WAI-ARIA-PRACTICES-1.2 forever?).

12. @michael-n-cooper also said, "...except for cross references with the ARIA suite where the version dependencies are more specific". I am not quite sure which references count as "cross references with the ARIA suite". Thoughts on that below:

I found 2 places in the ARIA spec that mention "the ARIA suite":
  1. "This document is part of the WAI-ARIA suite described in the [WAI-ARIA Overview](http://www.w3.org/WAI/intro/aria.php)."
  2. "WAI-ARIA 1.2 is a member of the [WAI-ARIA 1.2 suite](https://www.w3.org/WAI/intro/aria) that defines how to expose semantics of WAI-ARIA and other web content languages to accessibility APIs."

Note that both of those links redirect (should they be updated?) to a [WAI-ARIA Overview](https://www.w3.org/WAI/standards-guidelines/aria/) page, which has some pretty out-of-date content:
- it mentions Ajax several times, plus DHTML and HTML 5.1
- it says "WAI-ARIA 1.1 is expected to include only a few changes from 1.0. [Most potential changes will be considered for WAI-ARIA 2.0.]"
- the [current status of WAI-ARIA development FAQ](https://www.w3.org/WAI/ARIA/faq#update) was last updated in March 2014
- is the [WAI-ARIA 1.0 User Agent Implementation Guide](https://www.w3.org/TR/wai-aria-implementation/) from 2014 still relevant?
- it needs a whole new WAI-ARIA 1.2 section

I can [report issues for the WAI-ARIA Overview page](https://github.com/w3c/wai-intro-aria/issues) (is anybody watching that repo?), but I think fixing it is beyond the scope of this issue.

So, back to my assertion that the version number should be deleted from ALL references to CORE-AAM, ACCNAME, and WAI-ARIA-PRACTICES, the **only** place in the ARIA spec where I think it makes sense to keep those version numbers (and bump them up to 1.2) is in the list of supporting documents in the [Target Audience](https://w3c.github.io/aria/#target-audience) section. This list uses direct links, not [[references]]. Should it use references as well?

**Comment by michael-n-cooper** [comment]
On 13/04/2020 4:16 p.m., Carolyn MacLeod wrote:
>
> This issue is more involved than it seemed at first glance (i.e. it's 
> about much more than just making sure APG references are 
> non-normative). So I need to check some assumptions. Anybody who knows 
> any answers, please chime in:
>
> 1.
>
>     In the |respecConfig| json at the beginning of the doc,
>     |accNameURLs|, |coreMappingURLs|, and |practicesURLs| are all
>     currently at 1.1. I think they all need to be bumped up to 1.2 -
>     correct?
>
Yes, these should be updated to the latest version that we want to 
reference. They are substituted into links with special class attributes 
by the script, to help keep things tied together. I've been meaning to 
overhaul this to make it simpler to maintain but haven't sat down to it.
>
> 1.
>
>
> 2.
>
>     |ariaSpecURLs| in |respecConfig| is empty - is that intentional?
>
In the ARIA spec, we don't need that value because it's self 
referential. In Core-AAM, for example, we would need the ariaSpecURLs 
but not the coreMappingURLs.
>
> 1.
>
>
> 2.
>
>     |doRDFa: '1.1',| is deprecated
>     <https://github.com/w3c/respec/wiki/doRDFa-(DEPRECATED)>. Shall I
>     just ignore that for now?
>
Yeah. I'm not sure what that does / did. Probably it was a switch for an 
option that is now just automatic so we could remove it.
>
> 1.
>
>
> 2.
>
>     CSS3-SELECTORS has moved on to CSS Selectors Level 4
>     <https://www.w3.org/TR/selectors/>. (Someday, there may or may not
>     be an actual CSS4
>     <https://github.com/w3c/csswg-drafts/issues/4770>, but for now, we
>     should bump up the CSS Selectors version).
>
Sounds good.
>
> 1.
>
>
> 2.
>
>     DOM4 should just be DOM.
>
Agree.
>
> 1.
>
>
> 2.
>
>     Do we want to bump DPUB-ARIA-1.0 up to DPUB-ARIA-1.1? Or maybe
>     simply keep it version-less as DPUB-ARIA
>     <https://w3c.github.io/dpub-aria/>?
>
I think we should stay versioned, so that years down the road people 
following links from old documents will find cross references that have 
relevant content. I'm not sure if we've started work on DPub ARIA 1.1, 
but once we do we should update that reference.
>
> 1.
>
>
> 2.
>
>     We should probably keep SVG2 for now (and not change the reference
>     name to SVG). However, note that there's a normative [SVG2]
>     reference and an informative [SVG] reference, which oddly pulls in
>     a link to the latest SVG with mismatched link text for SVG 1.0. We
>     should probably update our ref to SVG2 (keep normative?), and the
>     reference database <https://github.com/tobie/specref> should
>     probably be updated to at least fix the link text. Anybody know
>     where the [SVG2] reference is defined? I only see SVG1 in our
>     biblio.js, and SVG10 (alias: SVG) and SVG112 (alias: SVG11) in the
>     reference database biblio.json.
>
We should definitely use just one form of the reference (SVG2, not SVG 
in this case). We probably don't need the version in our local biblio.js 
anymore, we should use the stock one from the reference database. It's 
automatically generated so I don't know if we can change the link text. 
The data is in https://api.specref.org/bibrefs?refs=SVG2 and should 
match information from https://www.w3.org/standards/history/SVG2.
>
> 1.
>
>
> 2.
>
>     Do we want to update our MSAA, UI-AUTOMATION and UIA-EXPRESS links
>     so that they are not redirected?
>
Yes, if there is a good permanent URI.
>
> 1.
>
>
> 2.
>
>     There's a reference to the previous version of the ARIA spec in
>     the Abstract <https://w3c.github.io/aria/#abstract> section at the
>     beginning of the document. The reference is currently being
>     interpreted as informative. Should I change that to normative
>     (i.e. using |[[!doc]]|)? Or is the previous version of a spec
>     considered to be informative after the new normative version is
>     published?
>
In the Abstract that should be informative because that's a 
non-normative section. If we want a normative reference to the previous 
version, we should introduce some wording somewhere in a normative 
section that gives us an opportunity for a normative reference.
>
> 1.
>
>
> 2.
>
>     @michael-n-cooper <https://github.com/michael-n-cooper> said, "In
>     general we use non version specific references". Currently, all
>     references to CORE-AAM, ACCNAME, and WAI-ARIA-PRACTICES contain
>     the 1.1 version number, i.e. CORE-AAM-1.1, ACCNAME-1.1,
>     WAI-ARIA-PRACTICES-1.1. /*I believe the version number should be
>     deleted from ALL references to CORE-AAM, ACCNAME, and
>     WAI-ARIA-PRACTICES in the ARIA spec*/. Please confirm, after
>     reading the rest of this issue comment.
>
I keep forgetting what we agree among the editors for this, so I'm not 
sure I have an authoritative reply. My take is we should use 
version-specific references for cross references between the suite, so 
the cross references go to versions that were designed to work together. 
In theory, we could eventually have ARIA 1.5, Core-AAM 1.5, AccName 1.2, 
DPub-ARIA 1.3 depending on ARIA 1.4, whatever. So having 
version-specific cross references keeps things tied together in the way 
we intended. However, for references outside the suite, particularly 
non-normative references, it's better to use versionless references to 
avoid things breaking, which is why we reference just "HTML" now.

This may be something to reconfirm in the editors group though.

> 1.
>
>
> 2.
>
>     @mcking65 <https://github.com/mcking65> Please double-check and
>     confirm that you want the WAI-ARIA-PRACTICES-1.1 reference in
>     combobox <https://w3c.github.io/aria/#combobox> (right before the
>     Characteristics table) to point to the latest, i.e.
>     WAI-ARIA-PRACTICES with no version (or do you want it to
>     specifically point to WAI-ARIA-PRACTICES-1.2 forever?).
>
> 3.
>
>     @michael-n-cooper <https://github.com/michael-n-cooper> also said,
>     "...except for cross references with the ARIA suite where the
>     version dependencies are more specific". I am not quite sure which
>     references count as "cross references with the ARIA suite".
>     Thoughts on that below:
>
I define the ARIA suite as the stuff published to TR as part of ARIA, 
which include ARIA itself, Core-AAM, AccName, Practices, and the other 
extension modules and accessibility API mappings such as dpub-[aria|aam] 
etc.
>
> 1.
>
>
> I found 2 places in the ARIA spec that mention "the ARIA suite":
>
>  1. "This document is part of the WAI-ARIA suite described in the
>     WAI-ARIA Overview <http://www.w3.org/WAI/intro/aria.php>."
>  2. "WAI-ARIA 1.2 is a member of the WAI-ARIA 1.2 suite
>     <https://www.w3.org/WAI/intro/aria> that defines how to expose
>     semantics of WAI-ARIA and other web content languages to
>     accessibility APIs."
>
> Note that both of those links redirect (should they be updated?) to a 
> WAI-ARIA Overview <https://www.w3.org/WAI/standards-guidelines/aria/> 
> page, which has some pretty out-of-date content:
>
>   * it mentions Ajax several times, plus DHTML and HTML 5.1
>   * it says "WAI-ARIA 1.1 is expected to include only a few changes
>     from 1.0. [Most potential changes will be considered for WAI-ARIA
>     2.0.]"
>   * the current status of WAI-ARIA development FAQ
>     <https://www.w3.org/WAI/ARIA/faq#update> was last updated in March
>     2014
>   * is the WAI-ARIA 1.0 User Agent Implementation Guide
>     <https://www.w3.org/TR/wai-aria-implementation/> from 2014 still
>     relevant?
>   * it needs a whole new WAI-ARIA 1.2 section
>
> I can report issues for the WAI-ARIA Overview page 
> <https://github.com/w3c/wai-intro-aria/issues> (is anybody watching 
> that repo?), but I think fixing it is beyond the scope of this issue.
>
The ARIA overview isn't maintained by the ARIA WG, though I'm supposed 
to keep an eye on not letting content fall out of date (obviously 
dropped it on that). The repo is watched by Shawn Henry, who works with 
the Education and Outreach Working Group.
>
> So, back to my assertion that the version number should be deleted 
> from ALL references to CORE-AAM, ACCNAME, and WAI-ARIA-PRACTICES, the 
> *only* place in the ARIA spec where I think it makes sense to keep 
> those version numbers (and bump them up to 1.2) is in the list of 
> supporting documents in the Target Audience 
> <https://w3c.github.io/aria/#target-audience> section. This list uses 
> direct links, not [[references]]. Should it use references as well?
>
Technically it's best to use formal references wherever we point to a 
doc, though in an introductory section we might opt for easier reading. 
Though I think we do want to keep the versioned references so the 
pointers across the suite stay valid later when new versions with 
potential non backward compatible changes are introduced.

**Comment by carmacleod** [comment]
PR https://github.com/w3c/aria/pull/1243 addresses the following points:

`4.` update CSS3 Selectors to CSS4

`5.` update DOM4 to DOM

`6.` I was wrong about DPUB-ARIA 1.1 - the latest recommendation is still 1.0, so no change

`7.` I was wrong-ish about SVG2 also - it is still in CR (since 2018). Nonetheless, I've updated our one SVG ref to SVG2 for consistency. I decided not to delete SVG1 from localBiblio in aria-common in case some other spec is still using it.

`8.` opened PR https://github.com/w3c/aria-common/pull/42 and PR https://github.com/tobie/specref/pull/598 to update Microsoft and macOS Accessibility API refs to link to permanent docs.microsoft.com URIs.

`3.` and `9.` are ignored.

**Note** that PR https://github.com/w3c/aria/pull/1243 does **not** address points `1`, `2`, `10`, `11` and `12` related to versioning of ARIA suite refs because that is being taken care of in PR https://github.com/w3c/aria/pull/1240, which also fixes the original normative vs. informative refs issue - in particular, it ensures that references to the APG are informative.
