### ISSUE TITLE
"This version" is no permalink in latest editor's draft

### ISSUE THREAD

**Issue by eps1lon** [w3c/aria#1294]
It should be a permalink in my opinion because otherwise a "this version" link becomes outdated once the editor's draft is updated. There' s also no "previous version" for editor's drafts: https://w3c.github.io/aria/

"this version" could point to the commit sha e.g. https://rawgit.com/w3c/aria/1d856c402eafbe7823021ff4cb5ca44dc1a9edf7/ and "previous version" could point to the parent commit.

For working draft and recommendation "this version" already is a permalink:
- https://www.w3.org/TR/wai-aria-1.1/
- https://www.w3.org/TR/wai-aria-1.2/

**Comment by cookiecrook** [comment]
WG discussion this morning was that there would be very little value in this, since GitHub shows commits, diffs, and already allows you to link to any commit SHA if needed. If people want permalink for reference, they can link by branch (including current master), or a more stable published version. In the rare case that someone needs to link a specific SHA, but publishing those as relevant "previous versions" could result in a proliferation of outdated links. 

Closing as "Behaves Correctly." Please reopen if you disagree.
