### ISSUE TITLE
Consider removing the word "mainstream" to describe "user agents"

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria#1321]
Several places in the spec say "mainstream user agents".
Each instance should be reviewed, and in most (all?) cases, the word "mainstream" should be deleted.

Note: wait until after https://github.com/w3c/aria/pull/1315 is merged.

**Comment by cookiecrook** [comment]
I agree with the removal in #1315, since that is an RFC-2119 statement, and it provides no additional value in that requirement. 

However, I'm not convinced that removing all instances of the word "mainstream" is necessary. I'm certain I wrote in a few of them to emphasize to the reader "this doesn't just mean AT." If these are considered individually and it's determined that every instance in informative prose is extraneous, I'm okay deferring to the editor's decision.

**Comment by scottaohara** [comment]
There are six mentions of "mainstream" in the spec.  Five of them used in combination with 'user agents', and one instance used to describe 'browsers'.

In reviewing these instances, I did find it curious that the abstract `landmark` role states:
>Mainstream [user agents](https://www.w3.org/TR/wai-aria-1.2/#dfn-user-agent) MAY enable users to quickly navigate to landmark regions.

and then `region` also states:
>Mainstream [user agents](https://www.w3.org/TR/wai-aria-1.2/#dfn-user-agent) MAY enable users to quickly navigate to elements with role region.

no other landmark roles re-states this. Instead they use the following:

>User agents SHOULD treat elements with the role of [ role here ] as navigational landmarks.


I think we should make `region` match the other landmark roles per this wording.  Additionally, i think it might be worth modifying `region` and `form` to mention they need to be named, to further align with the work i did in #1699

**Comment by scottaohara** [comment]
There are six mentions of "mainstream" in the 1.2 spec. Five of them used in combination with 'user agents', and one instance used to describe 'browsers'.

There are only four in the latest draft.  One of the ones that was removed since 1.2 was in reference to the region role.  A similar instance of "mainstream user agents" still is present with the `figure` role, and it is now the only role that references "mainstream user agents".

I think we could probably remove this one instance and leave the others.
