### ISSUE TITLE
Small but important omission in option role spec

### ISSUE THREAD

**Issue by brennanyoung** [w3c/aria#1357]
https://www.w3.org/TR/wai-aria-1.2/#option

The first line says "A selectable item in a listbox." That's not the whole truth.

The spec then goes on to mention that it can be a descendant of group, and this is mentioned again in the characteristics table.

To improve clarity and consistency here, could we please change the first line to

"A selectable item in a listbox or group." 

Thank you!

**Comment by JAWS-test** [comment]
I would not consider the sentence "A selectable item in a listbox or group." an improvement and find the current wording optimal and correct, because an option may only occur in a listbox, but a group may also occur outside a listbox. The current sentence would only be wrong if it said that option is always a direct child role of listbox.

However, it would be better to write in the table row "Required Context Role"  for option: "listbox, listbox  →  option"
This also applies to many other nested rolls. As a positive example I refer to [Grid](https://www.w3.org/TR/wai-aria-1.2/#grid):

> Required Owned Elements: row, rowgroup → row

**Comment by brennanyoung** [comment]
What about a group inside a graphics-symbol? See https://github.com/w3c/aria/issues/1358

**Comment by JAWS-test** [comment]
Currently option is only allowed in listbox. There is no hint that option could be allowed in graphic-object.

Important: Also in ARIA (without graphic module) there are many allowed uses of group, but group may only contain options if it is inside listbox

**Comment by brennanyoung** [comment]
The hint is implicit in the note. It says that `group` is a viable fallback for `graphics-object`, if support for ARIA 1.x is required. This suggests that a `graphics-object` has something in common with a `group`, or even that it is a 'kind of' `group`.

Therefore, a `graphics-object` which permits selections of its descendants might (in some cases) need to support `option` as a descendant role.

**Comment by JAWS-test** [comment]
Group is only a fallback for graphics-object. Many roles could have group as fallback like main, article, figure, radiogroup etc.

This does not change the fact that group is a very universal role, but may only contained options within listbox

**Comment by scottaohara** [comment]
Agree with @JAWS-test.  The spec states that an `option` is "A selectable item in a listbox."

inferring that it can be just added as a child of a `group` disregards the text that states that `group` must be a child of a `listbox`

**Comment by carmacleod** [comment]
I also agree with @JAWS-test, and I like the idea of making the spec even clearer by listing `listbox → group` under Required Context Role, instead of just `group`. PR #1359 adds this containment relationship to the Characteristics table for `option`, `treeitem`, and `menuitem[checkbox|radio]`.
