### ISSUE TITLE
Consider a new aria-live property that reads on page load

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria#1360]
Perhaps there is a use case for a new aria-live property that announces on page load... here are a few scenarios where it might be useful.

- A user submits a form and they are taken to a new page that has text "you successfully submitted the form". The live region would allow that page to read the message  first automatically after the user hits submit without forcing the user to navigate through the page to find the message.

- A user logs into their account on a store site. The page refreshes with a message, "you now are logged it"

- A server side based search system refreshes the pages after the user types a search term and hits submit and the page is refreshed with a the text "25 results for snowblowers."

Currently to announce something to a screen reader in these situations we are loading the page with an empty live region and then injecting the the message 500ms later, which seems clunky and hacky.

How about in additions to 
```aria-live="polite"``` and ```aria-live="assertive"```

that we add something like

```aria-live="pageload"```

**Comment by JAWS-test** [comment]
I don't understand why we need a new aria-live property, because I don't see the difference to aria-live=polite. 

> Currently to announce something to a screen reader in these situations we are loading the page with an empty live region and then injecting the the message 500ms later, which seems clunky and hacky.

This behavior would probably also apply to aria-live="pageload". A simpler change would be to change that live regions are also output by screenreaders when they are inserted dynamically.

**Comment by JAWS-test** [comment]
Perhaps three values for aria-live would be worth considering:

* polite: is only output at the end and only if the live region is in the visible area. Several updates within the same region, which has aria-live=polite, are not output one after the other, but always only the last one (e.g. for a progress bar, so that not all value changes are output, but only those for which there is time, otherwise there is often the problem that numbers are still output when the progress is already finished)
* medium: is only output at the end, but also if the live region is not in the visible area. Multiple updates within an aria-live=medium region are all output in sequence.
* assertive: Interrupts all other output, will be output even if the browser tab has no focus

**Comment by sinabahram** [comment]
@DavidMacDonald  is this not handled by existing events for onLoad, onReady, etc. with an announcer div being used either with polite or assertive aria-live values either with or without a an additional timeout to ameliorate AT page summary announcement interruptions? I'm having trouble coming up with a use case not addressed by that strategy.

**Comment by vanitabarrett** [comment]
In the GOV.UK Design System we can see a need for something like this with a couple of our components, specifically the [error summary](https://design-system.service.gov.uk/components/error-summary/) and the [notification banner](https://design-system.service.gov.uk/components/notification-banner/), which often need to be read out on page load so the user is aware that new information has appeared without having to navigate through the page content to get to it. 

An example might be: a user accidentally submits a form without filling out a required field. They need to be told on page load that the form submission has not been accepted. A screenreader user who cannot visually see the error messages on the page may initially be confused when they are brought back to the same page and no error message is automatically read out.

At the moment, we’ve implemented this by moving focus to the component using JavaScript (and adding `role=“alert”` to mitigate poor focus management by some screenreaders), but this solution is handled inconsistently by assistive technologies and relies on having JavaScript enabled to work.

**Comment by scottaohara** [comment]
With all due respect, doesn't that mean a solution exists right now, but it's implementations that are the issue?  I.e., if ATs would consistently announce live regions such as an `alert` on page load, then this use case would be accounted for.

I would be worried that introducing another type of live region would just add to the pile of issues with inconsistently implement live regions.

**Comment by sinabahram** [comment]
@vanitabarrett  if this existed, it would be under ARIA. Are there ARIA-aware browsers you are targeting that simultaneously do not support JavaScript? That's an interesting carveout, and nothing immediately comes to mind.

Going back to my original question, which @scottaohara  also echoed, is this not already facilitated by aria-live? Wouldn't you have even more, not less, success with a new aria-live value, as it would take a nontrivial number of years to reach the same level of inconsistent support that you are currently experiencing across AT/browser combinations?

It feels like there is a real problem here, but that the solution is to push on browsers and AT vendors to get the existing technologies working well as they can facilitate your use case fully.

**Comment by DavidMacDonald** [comment]
@sinabahram 

I've been doing a bit of testing... (In Chrome)

- JAWS will announce a static element with role="alert" on page load
- NVDA won't announce a static element with role="alert" but will read if an onload event is fired like below
-VoiceOver won't read either

I think in this case JAWS has it right... and we wouldn't need another attribute IF the other screen readers did the same.

```
<body  onload="smessage">
...
<div id="success" role="alert"></div>
...
<script>
function srmessage() {
document.getElementById("success").innerHTML = "Your purchase was a success!";
}
</script>
</body>
```

**Comment by sinabahram** [comment]
Sounds like a plan, and feel free to CC me @DavidMacDonald on those bugs if I may add support as a native user voice of all those things.

**Comment by JAWS-test** [comment]
@DavidMacDonald 

Your two examples (with and without JS) both do not work with JAWS when aria-live=polite or assertive is used instead of role=alert. Therefore, JAWS has a problem here too. Just as there are many other [problems with live regions in JAWS](https://github.com/FreedomScientific/VFO-standards-support/issues?q=is%3Aissue+is%3Aopen+live+region)
