### ISSUE TITLE
Conflict when using aria-roledescription and attributes that affect the role

### ISSUE THREAD

**Issue by JAWS-test** [w3c/aria#1373]
There are some widgets where the role depends not only on the role, but also on attributes, e.g.
* button with aria-pressed becomes toggle button
* listbox with aria-multiselectable=true becomes extended listbox
* slider with aria-orientation becomes a left-right or up-down slider

If such an element is now provided with its own role description using aria-roledescription, the information of the ARIA attributes (such as aria-pressed, aria-orientation or aria-multiselectable) is lost, because they are only output as part of the role, but the role is overwritten. Maybe the ARIA specification should regulate this special case more precisely. 

I can think of two possibilities:
* The ARIA specification rules that AT must output the attributes in all cases. This would be the simpler variant
* The ARIA specification rules that the web developers must pass the attribute information inside aria-roledescription. This would be the difficult variant, because then the ARIA specification would have to define beforehand the behavior described above (i.e. the fact that certain attributes are not output as attributes, but lead to a change of role. This is currently not defined, so that each AT can output this differently).

**Comment by carmacleod** [comment]
These roles can also be changed by an attribute:
- button with aria-haspopup=true or menu becomes menu button
- region or form with aria-label[ledby] becomes landmark

As @stes-acc says, we need to sharpen the definition of aria-roledescription.
We may want to merge this issue and #1372 into #1132, and address all 3 issues together.

**Comment by stes-acc** [comment]
Results of deep dive on the topic:

1.	It is helpful  to mention base role in roledescription when using roledescription on widgets. The ARIA spec https://w3c.github.io/aria/#aria-roledescription chapter can be improved with a sentence explaining this.

2.	Any text not mentioning base role when using roledescription on widgets is problematic since it masks base role and is therefore considered as authoring error. Bad practices get no special mentioning neither in the ARIA specification nor the ARIA APG.

3.	It is expected that for overrides of base role of region containers etc. using roledescription on widgets, the roledescription is spoken instead the base role when focusable descendants are focused. Observed violations can be filed to the AT vendor and are expected to be acknowledged and fixed.

4.	The reason for overriding base role speech output with roledescription content was decided on group consensus when the property has been introduced to AT as result of feedback of blind users that were confused by double-speak of roledescription and base role. 

5.	The group has created a respective special issue [https://github.com/w3c/aria/issues/1480)] where all further discussion should be continued.

6.	Update with this info:

[18:08] <StefanS_> [https://github.com/w3c/aria/issues/1373]
[18:08] <StefanS_> [https://github.com/w3c/aria/issues/1132]
[18:09] <StefanS_> [https://github.com/w3c/aria/issues/1372]
