### ISSUE TITLE
Presentational role conflict resolution and aria-hidden=true

### ISSUE THREAD

**Issue by dd8** [w3c/aria#1388]
The draft spec currently says :

> If an element has global WAI-ARIA states or properties, user agents MUST ignore the presentation role and expose the element with its implicit role.

https://rawgit.com/w3c/aria/master/#conflict_resolution_presentation_none

That looks like it does the wrong thing in this case since aria-hidden is a global state:

```
<img role='presentation' aria-hidden='true' />
```

Following the MUST wording in the spec:

```
<img role='presentation' /> <!-- not in accessibility tree -->
<img aria-hidden='true' /> <!-- not in accessibility tree -->
<img role='presentation' aria-hidden='true' /> <!-- triggers conflict: exposed with implicit role=img -->
```

**Comment by JAWS-test** [comment]
I don't really see a problem there, but I also don't mind a clarification in the specification.

1st step: global ARIA attribute leads to role=presentation not working
2nd step: global ARIA attribute does what it does, i.e. in case of aria-hidden=true hide the element (whether with or without role)

**Comment by dd8** [comment]
I think the problem is "MUST" is defined in RFC 2119 as:

> 1. MUST   This word, or the terms "REQUIRED" or "SHALL", mean that the
   definition is an absolute requirement of the specification.

https://tools.ietf.org/html/rfc2119

So there's an absolute requirement to expose the example as role=img

Core AAM says:

>aria-hidden=true on unfocused element
> Element SHOULD NOT be exposed

https://www.w3.org/TR/core-aam-1.2/

So the MUST takes precedence over the SHOULD NOT.

**Comment by scottaohara** [comment]
I still don't see a problem here.  

Yes, the `role=presentation` would be ignored and the default role would be exposed.  However, you then seem to take it to the next level that because of the MUST to expose the default role, that therefore `aria-hidden=true` cannot be allowed to perform its function to hide the **element** from the accessibility tree - which is more than just about hiding its role.

Using an example that wouldn't produce an HTML validation error ("An `img` element with no `alt` attribute must not have a role attribute.")

`<p role=presentation aria-hidden=true>My content</p>`

1. paragraph role is suppressed by role=presentation
2. global aria attribute re-exposes role of paragraph
3. aria-hidden=true hides the entire element from the accessibility tree.

**Comment by scottaohara** [comment]
Would the following text change help clarify this?

>If an element has global WAI-ARIA states or properties, user agents MUST ignore the `presentation` role and instead expose the element's implicit role.
