### ISSUE TITLE
Does "Conflicts with Host Language Semantics" also apply when an attribute is implicit

### ISSUE THREAD

**Issue by JAWS-test** [w3c/aria#1433]
https://www.w3.org/TR/wai-aria-1.1/#host_general_conflict

> When a host language declares a WAI-ARIA attribute to be in direct semantic conflict with a native attribute for a given element, user agents MUST ignore the WAI-ARIA attribute and instead use the host language attribute with the same implicit semantic.

I understand this to mean that when `required` and `aria-required` are used, the HTML attribute is used and the ARIA attribute is ignored. If this is correct, I wonder what applies when an HTML element has an implicit ARIA attribute, such as `<h1>` implicitly has `aria-level=1`. Can I now use 

`<h1 aria-level=2>`

to override the implicit `aria-level=1`?
It seems to me that this is not currently covered in the specification.

The browsers answer the question as follows:
* Firefox, Edge, Chrome: Yes, `aria-level=2` can override the level of `<h1>`.
* IE 11: No

**Comment by MelSumner** [comment]
Since `aria-level` is not an HTML attribute, your example would fall into the highly-ill-advised-but-still-technically-correct category. 

I believe the current language _does_ cover the example you provided, following explicitly what is written. The host language (in this case, HTML) doesn't have a _native_ (meaning, native HTML) attribute (even if it has an implicit ARIA attribute).
