### ISSUE TITLE
HTML-AAM: <dfn> UIA mapping to group with localized control type and text style

### ISSUE THREAD

**Issue by cyns** [w3c/aria#145]
control type: group
localized control type: definition
If the text is rendered in Italics, the text pattern will have italic style

**Comment by jasonkiss** [comment]
Done. Closing on the assumption that the sentence re text styling being exposed by UIA text attribute identifiers of the TextRange control pattern implemented on a parent accessible object is acceptable.

**Comment by jasonkiss** [comment]
Reopening as I noticed that in latest stable channel release of Edge (14393), `dfn` gets an accessible object with Text Control Type. Agree this should be Group, given `dfn` content model (flow content), but just want to confirm that it should get an accessible object by default, because the UIA mapping currently states "No accessible object". @cyns?

**Comment by jasonkiss** [comment]
This issue was moved to w3c/html-aam#7
