### ISSUE TITLE
HTML-AAM: mappings for dd, dt, dl seem insuficient

### ISSUE THREAD

**Issue by cyns** [w3c/aria#148]
Consider adding a "term" role to aria? It doesn't seem like the current mapping provides enough info to AT.

**Comment by jasonkiss** [comment]
If [role=term (ARIA1.1)](http://w3c.github.io/aria/aria/aria.html#term) is confirmed, this could work nicely:

- `<dl>`: Seems this is referred to in HTML5.1 as description list instead of definition list. In UIA, this could get localized control type "description list". AX could update its AXSubrole to AXDescriptionList, or at least its AXRoleDescription to "description list". Or we could stick with using "definition list" in both cases.
- `<dt>`: Could map to role=term (as could `<dfn>` for that matter)
- `<dd>`: Is already mapped to role=definition

**Comment by jasonkiss** [comment]
This issue was moved to w3c/html-aam#8
