### ISSUE TITLE
Revert new labeling mechanisms

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria#1490]
Revert figure, fieldset, legend

**Comment by mcking65** [comment]
I don't have links to meetings where this was discussed, but think it is important to document the rationale for discarding this proposed feature.

We originally added the additional labeling mechanisms because we thought that the ideal way to provide role parity for the HTML label element would be to have an ARIA label role that can encapsulate the element being named. Taking this approach turns out to be a very heavy lift for browsers; it is a significant change to name calculation.

From a naming perspective, the aria-labelledby attribute provides authors the same capability as the HTML label element. Thus, we concluded that ARIA does not need a label role to provide parity with the HTML label element.

Given the signifcant implementation cost of this feature and the understanding that it is more of a coding convenience than a necessaty, the consensus is to not go down this path for now.
