### ISSUE TITLE
CORE-AAM: AXRoleDescription for "contentinfo" should be "content information"

### ISSUE THREAD

**Issue by cyns** [w3c/aria#155]
Should we use "header" rather than "banner" and "footer" rather than "content information" for user-facing strings in both HTML and ARIA mappings?
Why?
1) Header and Footer are parallel concepts. 
2) Header and Footer are less esoteric concepts. they are words that more regular users will understand.
3) "banner" is confusing. People think it means "banner ad" and expect it to be an image type
4) "content info" is not a meaningful term to regular users.

Not all content info is a footer, so maybe the aria role=contentinfo should still be exposed as "content information". However, HTML &lt;footer&gt; should be exposed as "footer"

**Comment by jasonkiss** [comment]
> 2) Header and Footer are less esoteric concepts. they are words that more regular users will understand.

True, although the word "header" is used to refer to headings, table column headers, as well as page or section headers. So it may equally cause some confusion. 

> 3) "banner" is confusing. People think it means "banner ad" and expect it to be an image type

Personally, I suspect users will get familiar with "banner" as a type of landmark since that's always going to be the context in which they encounter this particular use of "banner". 

> 4) "content info" is not a meaningful term to regular users.

In CORE-AAM, there is no necessary HTML context, so user-localized strings should reflect the landmark, which they currently as listed. "Content information" is a little better, but agree it's pretty meaningless. Both UIA and AX specify "content information" as the localized string for the raw landmark, although it looks like Edge is still using "content info" as the LocalizedControlType in that instance.  

Note: @klown, AXRoleDescription for "contentinfo" needs to be updated to "content information" in CORE-AAM as per http://trac.webkit.org/changeset/110825/trunk/Source/WebCore/platform/LocalizedStrings.cpp

Regarding the UIA and AX mappings in the HTML-AAM, see [html-aam issue #10](https://github.com/w3c/html-aam/issues/10).

Since HTML-AAM has moved, and the issue seems settled for UIA in CORE-AAM, I've renamed the issue to reflect fix needed for "contentinfo" AX mapping in CORE-AAM.

**Comment by joanmarie** [comment]
Change made. Closing.
