### ISSUE TITLE
Author test case: 4.3.1 manage focus (ARIA 1.2)

### ISSUE THREAD

**Issue by cyns** [w3c/aria#1560]
4.3.1 – Information for Authors Authors MUST manage focus on the following container roles:
• grid • listbox • menu • menubar • radiogroup • tree • treegrid • tablist

**Comment by spectranaut** [comment]
How do you even write a test for this? Is it possible?

**Comment by joanmarie** [comment]
Anything is possible. :) But in terms of writing a test for validators for the sake of getting a spec out the door, I'm leaning towards not writing a test for this.

Were someone to insist that a test must be written for this statement, and there were validators with the functionality of "hey, did you know you needed to do this? Just pointing it out in case you didn't", then I'd write a test that used those roles in order to verify that a helpful info message was provided.

**Comment by spectranaut** [comment]
that would be nice :) but for now, should we close this issue? We don't know when or if such a validator will exist so it seems weird to keep it open IMO. Or, maybe there should be an backlog issue for "All unvalidatable `author MUST` statements".

**Comment by joanmarie** [comment]
Let's leave it open for a while and see if any other WG members think we should write a test.

**Comment by jnurthen** [comment]
RESOLUTION from Sept 2 2021 ARIA WG meeting to close this
