### ISSUE TITLE
Updating ARIA 1.2 due to IDL implementations (exit and re-enter CR?)

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#1598]
As described in https://github.com/w3c/aria/issues/1585#issuecomment-893892641 as well as in ARIA WG meetings [1](https://www.w3.org/2021/07/29-aria-minutes.html#t08) and [2](https://www.w3.org/2021/08/12-aria-minutes.html#t06), what implementors have done for ARIA reflection does not appear to match what is in the spec.

In particular, default/implicit values for missing attributes are not being reflected, and no validation is taking place. When an attribute is not present in the DOM, the reflected value is null. Thus as it currently stands, I believe we have 0 implementations for the IDL interface as spec'ed in ARIA 1.2.

What is currently implemented seems consistent with the properties being a nullable `DOMString`. Therefore, unless there is a strong belief that what is in the spec now (attributes are a non-nullable `DOMString`) is correct and that the implementations are wrong, the thing to do might be to update ARIA 1.2 to reflect (pun intended) reality.

**Comment by cookiecrook** [comment]
@cyns is [drafting some changes externally](https://docs.google.com/document/d/1_KNKQVTakhP11wekPWhT5FJTtknwJPE7heswUfhHfUs/edit#heading=h.ecvk7fee7mzh).

**Comment by cyns** [comment]
Here's the PR https://github.com/w3c/aria/pull/1611

**Comment by saschanaz** [comment]
> Therefore, unless there is a strong belief that what is in the spec now (attributes are a non-nullable `DOMString`) is correct and that the implementations are wrong, the thing to do might be to update ARIA 1.2 to reflect (pun intended) reality.

Probably worth to ping @annevk who raised #1058.

**Comment by annevk** [comment]
Was an effort made to get implementations to change here? Are there tests? This change was made only a year ago too.

Furthermore, it's not clear to me that the current text works as reflecting only supports nullable strings if the attribute is an enumerated attribute and meets the requirements thereof. See also the discussion in the issue @saschanaz referenced.

**Comment by cookiecrook** [comment]
We looked into changing the implementations, but it's a non-trivial amount of work with no clear user benefit. 

As such, we don't believe the engines need to change, so we'd like to take the WHATWG-recommended approach that you and others helped develop: update the spec to match what is already working in the implementations.

**Comment by annevk** [comment]
But what exactly is that? The PR doesn't appear to do that as far as I can tell. It relies on reflect, but reflect doesn't handle this type for numerous ARIA attributes.

**Comment by cookiecrook** [comment]
The PR diff is unreadable due to a branching error, but the only substantive IDL change in this PR is to add the nullable `?` to the existing DOMString entries like `ariaLabel`. It won't change any of the other `FrozenArray<Element>` attributes you're concerned about, like `ariaLabelledByElements`. The diff also adds some examples. HTH. (@cyns please verify I recall correctly)

**Comment by annevk** [comment]
It doesn't really, `ariaLabel` isn't an enumerated attribute as far as I know, so `DOMString?` doesn't work if you say "reflect".

**Comment by annevk** [comment]
cc @domenic

**Comment by cookiecrook** [comment]
I’ll defer to @joanmarie and @cyns on the resolution, since they discussed at more length and proposed the PR.

**Comment by cookiecrook** [comment]
@annevk wrote:
> as far as I know, so DOMString? doesn't work if you say "reflect".

When we first proposed adding IDL to ARIA, the standard version of IDL didn't include `reflect` at all. Since it's been a moving target, we appreciate your help in this area.

For the following HTML element:
```html
<div aria-label="foo"><!-- No role. This is just an example element for the output below. --></div>
```

This is the console output in WebKit, and IIRC, it matches other engines.
```console
> $0.ariaLabel
< "foo"
> $0.getAttribute("aria-label")
< "foo"
> $0.setAttribute("aria-label", "")
< undefined
> $0.getAttribute("aria-label")
< ""
> $0.ariaLabel
< ""
> $0.removeAttribute("aria-label")
< undefined
> $0.ariaLabel
< null
```

IIRC @joanmarie and @cyns were attempting to match the existing implementations, which treat these attributes like nullable, reflected DOMStrings, as demonstrated above. If there is a better syntax to express this in the current version of IDL, please advise. Thanks.

**Comment by saschanaz** [comment]
> We looked into changing the implementations, but it's a non-trivial amount of work with no clear user benefit.

I wonder what caused such amount of work, were there web compat issues?

**Comment by cookiecrook** [comment]
@cyns looked into this more for Chrome, but IIRC, the issue was that in every web engine, the backing accessibility implementation already handled validation, so implementing reflected enumerated attributes was a reasonable amount of effort with no end-user impact. This section was added to explain that.

> ### 6.3.1 IDL Reflection of ARIA attributes
> All ARIA attributes reflect in IDL as `DOMString` attributes. This includes the boolean-like enumerated `true/false` type, and all other ARIA enumerated attributes. 
> 
> Default values from the ARIA values tables MUST NOT reflect to IDL as the _missing value default_ or the _invalid value default_ for the attribute. On getting, a missing ARIA attribute will return `null`. ARIA attributes are not validated on get. If an ARIA value is invalid, on getting, it will return its set value as a literal string, and will not return an invalid value default.
> 
> ### 6.3.2 Operating System Accessibility API mapping of ARIA enumerated attributes
> Unlike IDL reflection, operating system accessibility API mappings of ARIA enumerated attributes do have defaults. The default values from the ARIA values tables are exposed to the operating system accessibility API as described in section 5.2.3 Supported States and Properties of this specification, and in the CORE-AAM specification.

**Comment by saschanaz** [comment]
It sounds like Chrome couldn't do something like this:

```cpp
Option<DOMString> AriaMixin::AriaLabel() {
  auto nullable = WhateverTheBackingAccessibilityImplDoes();
  if (nullable.is_null()) {
    return "";
  }
  return nullable.inner_value();
}
```

... which doesn't make sense to me, or I probably still lack the background here.

**Comment by annevk** [comment]
"Reflect" has been a concept defined by the HTML standard for well over a decade so I think there might be some misunderstanding here. At least per my understanding this feature is a lot newer than that.

**Comment by cookiecrook** [comment]
Clarifying that I was referring to the ~`[reflect]` syntax WebKit and Blink use(d?).

**Comment by annevk** [comment]
At the moment that's just an implementation detail. There's been some talk about standardizing it, but not a lot of progress. (It would still build upon "reflect" though so the issues would remain the same.)

**Comment by domenic** [comment]
To be a bit clear, since nobody has stated it this way: right now your spec has a (conceptual) null pointer exception, since you apply the concept "reflect", but in spec-land that concept is totally inapplicable to `DOMString?` attributes. So anyone trying to implement based on the spec you have written (plus the HTML spec) is unable to do so.

**Comment by cookiecrook** [comment]
After some additional digging and discussion with colleagues, I think there is a path forward.

### ARIA 1.2 
In order to get ARIA 1.2 through its long-overdue CR, remove the reference to HTML reflection and replace it with something like "Return the value of the attribute if present and null otherwise." This way the 1.2 spec still matches the shipping implementations. It can include in a Note the similarity/difference between this and HTML's concept of reflection.

### ARIA 1.3 or later 
Consider changing the implementations to non-nullable reflected DOMStrings... (@cyns, @joanmarie, and @aleventhal to comment, since IIRC, it was one of them who mentioned an implementation, interop, or scheduling concern.)

On the surface, it seems like this may be as simple as removing the `?` from the [WebKit IDL](https://github.com/WebKit/WebKit/blob/main/Source/WebCore/accessibility/AriaAttributes.idl) and [Chromium IDL](https://github.com/chromium/chromium/blob/master/third_party/blink/renderer/core/dom/aria_attributes.idl), but I'll defer to the others on the prior discovered concerns.

**Comment by jnurthen** [comment]
In HTML crossOrigin on `img` is defined as 
`[CEReactions] attribute DOMString? crossOrigin;`

with the following: 
The crossOrigin IDL attribute must reflect the crossorigin content attribute, limited to only known values.

I'm not sure what is different for our usage of reflect than this.

**Comment by annevk** [comment]
@jnurthen see https://github.com/w3c/aria/issues/1598#issuecomment-928903152. `crossorigin` is an enumerated attribute, `aria-label` is not.

**Comment by saschanaz** [comment]
`new Image().alt` returns `""` and (I think we can't change it as the behavior has been there for decades).

**Comment by cookiecrook** [comment]
@saschanaz wrote:
> Yeah and I don't think people are asking for the non-nullable behavior, it's just that the spec is broken and you need to define an actual algorithm for nullable non-enumerated string attributes.

Modifying this comment above to clarify a potential permanent solution rather than just a stop gap.
> …remove the reference to HTML reflection [for the non-enumerated attributes] and replace it with something like "Return the value of the attribute if present, or null otherwise." This way the 1.2 spec still matches the shipping implementations. It can include in a Note the similarity/difference between this and HTML's concept of reflection.

Note: The enumerated attributes in ARIA may be 1:1 with the [§6.7 list](https://w3c.github.io/aria/#state_prop_def) whose short description start with the word "Indicates…" (minus `aria-keyshortcuts` b/c of #1625)

I think these are the new choices based on @saschanaz's comment:

1.  Spec could state that the nullable enumerated attributes `reflect` (HTML definition), and the other nullable attributes, ~"Return the value of the attribute if present, or null otherwise." Downside to this path is that none of the implementations match the enumerated attributes IDL now, so those would need to be removed from the PR, or ARIA 1.2 CR would need to wait on two implementations for .

2. Spec could remove the `reflect` verbiage entirely, and define this algorithm for all nullable DOMStrings, ~"Return the value of the attribute if present, or null otherwise." Downside to this path is that we risk breaking webcompat for any we expect to be nullable enumerated attributes in the future. However, upside is that this matches the implementations today, so it's a very low risk that it would cause additional harm.
