### ISSUE TITLE
Consider removing the attribute keyword "Indicates" and change it to "Enumerates" 

### ISSUE THREAD

**Issue by cookiecrook** [w3c/aria#1627]
Related to #1625 and the IDL issues surrounding enumerated attributes.

Currently the descriptions for [all aria-* attributes](https://w3c.github.io/aria/#state_prop_def) start with one of three keywords:

- **identifies**, meaning the value will be an IDREF or IDREFS list
- **defines**, meaning the value will be a freeform string or number value, or
- **indicates**, which in hindsight probably means, or at least is very closely associated with the aria value types that will be nullable enumerated IDL attributes.

When looking at these in the context of IDL changes, I thought the group should consider removing the attribute keyword "Indicates" and change it to "Enumerates" to make this distinction more obvious.

**Comment by brennanyoung** [comment]
Doesn't "enumerate" mean to arrange a limited series of items in a specific order? To list them (all) in fact. 

In comp.sci. an "enumerated type" has specific meaning, and it is true that "an enumeration" (or more commonly "an enum") is loose jargon for one of the values defined by an enumerated type, which I think is what is being grasped for here.

But "to enumerate" does **not** mean to pick one, or point at one. It still means to **list**, **count** or **order** a finite set.

It's not a close synonym of "indicate".

If I understand correctly, you are keen to emphasise that the value is not 'free form', but must be chosen from a given set, right? And certainly, "indicate" does not quite capture this constraint, but "enumerate" is (I think) worse, since (outside the domain of dev jargon) it suggests counting/ordering a set rather than picking from that set.

**Comment by cookiecrook** [comment]
> Doesn't "enumerate" mean to arrange a limited series of items in a specific order? To list them (all) in fact.

As I understand it, the order matters for implementation (because the enumerated value is stored as a numeric key), but it doesn't really matter really in author usage. The author doesn't need to know if the "date" token of aria-current is implemented as 5 or 6. They only need to use the enumerated value "date"… 

These values defined for the are the complete list of enumerated tokens. For example, the [ARIA Value Type Mappings](https://w3c.github.io/aria/#typemapping) already declares these as a "name token with an enumeration constraint." Likewise, the HTML spec defines this type as [enumerated attributes](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#enumerated-attribute).

**Comment by cookiecrook** [comment]
So if not "enumerates" what word would you recommend?

**Comment by cookiecrook** [comment]
Closing as NTBF.
