### ISSUE TITLE
Question: role presentation on non-semantic elements - why?

### ISSUE THREAD

**Issue by LaurenceRLewis** [w3c/aria#1647]
In the ARIA 1.2 Spec for  [Role Presentation](https://www.w3.org/TR/wai-aria-1.2/#presentation) [Example 9](https://www.w3.org/TR/wai-aria-1.2/#example-9) has the following example:
`
<span role="presentation"> Sample Content </span>`
 
I am finding a lot of seemingly unnecessary uses of role presentation/none on non-semantic elements in the wild and when accessibility testing. The '_Depending on styling and other factors_' has no further explanation as to why styling or factors would require this role.

I have read that the Role Presentation/None can be used as a bug fix, but can't remember what it fixes.
 
I'd appreciate your opinion on this.

**Comment by pkra** [comment]
According to git, this line has not been changed in 7 years, so it's likely out of date. (Part 2 of that example is now also out of date since there's now a generic role.)

**Comment by pkra** [comment]
From today's call: the third example is related to https://github.com/w3c/aria/pull/1454 -- with some patterns (e.g., those needing aria-level), elements in between parent and children roles might require an explicit role=presentation. Otherwise, AT might get tripped up. [I hope I captured the group's discussion correctly.]

Once #1454 is done (on track for ARIA 1.3), we might be able to simply remove this. We might want to keep a note on the more complex situation as well.

(And again, the second example needs revisions as well.)

**Comment by scottaohara** [comment]
Seems to me we should clean up this example, if not for the fact that a `span` in aria 1.2 is noted as an HTML equivalent for `role=generic`, so this example is now not only unclear, but outdated in its accuracy.
