### ISSUE TITLE
HTML-AAM: UIA mapping for <legend>

### ISSUE THREAD

**Issue by cyns** [w3c/aria#172]
text
LabeledBy of parent fieldset points to this element

**Comment by cyns** [comment]
add participates in name calculation

**Comment by jasonkiss** [comment]
There is an explicit entry for fieldset and legend in the acc name and description section of the document. Is it necessary to include a note about legend participating in the name calculation? I don't think so, but if it is, wouldn't we want to be consistent and include such note for the other APIs, and for similar elements, e.g summary, caption?

**Comment by asurkov** [comment]
I think I'd rather had name computation and relations under each element.

**Comment by jasonkiss** [comment]
@cyns, @asurkov 

We don't document that many relations, so I'm happy with those being included on an element by element basis. But so many elements participate in their name calculation that I think it would get very repetitive to mention that for each element.

@asurkov Do you have particular concerns with the name computations being in their own section and separate from the individual element mappings?

**Comment by asurkov** [comment]
@jasonkiss I think I'd rather had the element oriented structure as it's supposedly easier for implementers. That would require drastic the spec structure changes though. I can live with the current structure, if the majority find it optimal, but I might missed your question.

**Comment by jasonkiss** [comment]
@asurkov You answered my question, thanks. Yes, integrating the name computation with each element's other mappings is a big change and I don't see it happening any time soon, given the increasing number of AAM specs using the current common structure. 

@cyns @asurkov I'm going to propose that instead of adding "participates in name calculation" or similar to every element that participates in its own or another element's name calculation, we include a note in the "Notes" section preceding the mapping table. This note just reminds implementers to check the Accessible Name and Description Calculation section for how elements' names and descriptions are calculated, where applicable. See http://rawgit.com/w3c/aria/notes-to-html-role-mappings/html-aam/html-aam.html#html-element-role-mappings.

**Comment by asurkov** [comment]
this sounds good

**Comment by jasonkiss** [comment]
Addressed as described above in merged PR #424. Closing.
