### ISSUE TITLE
Further updates to caption role definition

### ISSUE THREAD

**Issue by scottaohara** [w3c/aria#1734]
Resurfacing a question I raised in #1703 so we can discuss / potentially create a separate PR.  

The `caption` role has author requirements/wording that would indicate that the placement of the caption is meaningful.  E.g., as the first child of a table or radiogroup, or the first or last child of a figure.  This mimics the requirements of the HTML equivalent elements (caption and figcaption), however in reality these placement requirements have no practical benefit.

This could be changed in the future, if ARIA reintroduces/works on the idea of naming by encapsulation - but for now the rules just add author complexity without any practical benefit.

So, the options I see here are to revise/remove the placement rules to loosen unnecessary requirements on authors.  Or, keep them mostly as-is, but preface the requirements with an **if**.  I.e., it's fine if your caption is marked up outside of a `radiogroup`, but if it's a child of that `radiogroup` it SHOULD be the first child...

**Comment by MelSumner** [comment]
Weighing in: 

1. as a tooling author, I like really specific rules, because it makes it easier for me to write linting or testing rules
2. as a code author, I prefer specific rules, because it gives me greater confidence that my code is correct.

**Comment by scottaohara** [comment]
resolution:  keep descendant requirements here, but loosen the restrictions on needing to be a 'direct' child.

**Comment by cookiecrook** [comment]
I'm all for loosening unnecessary restrictions on authors. 

I wish @MelSumner's view expressed above represented a majority opinion among web developers, but there are so many careless [non-]practitioners of web accessibility that we should err on the side of the assistive technology user. They will need to use both the sites exquisitely coded (by developers like @MelSumner) as well as the sites coded by careless web developers. 

I think we should build the resiliency into the browser engine and AT, rather than relying on every web developer to do the right thing.
