### ISSUE TITLE
restrict aria-owns on roles with children presentational

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria#1760]
# Description of bug or feature request

follow on from PR https://github.com/w3c/aria/pull/1733

## Will this require a change to [CORE-AAM](https://w3c.github.io/core-aam/)?

If unknown, leave blank. If relevant, link bug.

## Will this require a change to the [ARIA authoring guide](https://w3c.github.io/aria-practices/)?

If unknown, leave blank. If relevant, link bug.

# PR tracking (for feature tracking, leave as is when submitting)

* ARIA PR:
   * Editor's Draft commit:
   * Working Draft commit:
* Core AAM PR:
* AccName PR:
* APG PR:

# Implementation tracking (for feature tracking, leave as is when submitting)

* WPT test:
* Implementations (link to issue or when done, link to commit):
   * WebKit: [ISSUE]()
   * Gecko: [ISSUE]()
   * Blink: [ISSUE]()

**Comment by aleventhal** [comment]
Chromium/Edge (and I believe Firefox) do not actually truncate children for "children presentational" nodes. This is because authors sometimes actually put useful content in there, and truncating it would cause some pages to be less accessible. We expect the author to be warned by validation tools.

That said, Chromium does restrict some native elements from having children, such as `<br>` or `<input type=range>`. We do this for stability reasons.

I've written up a document of all the extra filtering rules Chromium applies to aria-owns, to help other browsers implement. It took quite a while to fully stabilize the aria-owns implementation, so I believe this document is quite valuable. Chromium no longer crashes even when aria-owns is applied randomly via fuzzers.
https://docs.google.com/document/d/1jhztcbvUWS4_QGtKmWMxVBLnMkl5ZAAqRCVTcLfdl4o/edit

**Comment by aleventhal** [comment]
It seems reasonable as an author error, but I probably wouldn't want to change the implementation.
