### ISSUE TITLE
Why table has "name required"

### ISSUE THREAD

**Issue by JAWS-test** [w3c/aria#1769]
# Describe your concern

An HTML table does not need a label. The caption element is optional. Why does an ARIA table require a caption?

# Link to the version of the specification or documentation you were looking at at.

Link to documentation: 
* https://w3c.github.io/aria/#table
* https://html.spec.whatwg.org/multipage/tables.html#the-table-element

Does the issue exists in [the editors draft](https://w3c.github.io/aria/) (the editors draft is the most recent draft of the specification)? Yes

**Comment by curtbellew** [comment]
The ARIA table role infers tabular data whereas the table tag could be used for layout - not that common these days but still possible.   In other words, the ARIA table role is singular in purpose.  It is to present data and so it requires a name.

**Comment by JAWS-test** [comment]
@curtbellew 

I don't think that's correct. Also, according to the [WHATWG specification](https://html.spec.whatwg.org/multipage/tables.html#the-table-element), HTML tables are only allowed for tabular data and not for layout (see the quote below). Nevertheless, they do not need a name. Also, a list does not need an Accessible Name in either ARIA or HTML, even though a list is a simplified form of a table.

> Tables must not be used as layout aids. Historically, some web authors have misused tables in HTML as a way to control their page layout. This usage is non-conforming, because tools attempting to extract tabular data from such documents would obtain very confusing results. In particular, users of accessibility tools like screen readers are likely to find it very difficult to navigate pages with tables used for layout.

**Comment by curtbellew** [comment]
You are correct in part.  The spec is pretty franks about the intention is that a table should only be used for data but later in the spec they mention layout tables - because reality intrudes.

> If a [table](https://html.spec.whatwg.org/multipage/tables.html#the-table-element) element has a (non-conforming) [summary](https://html.spec.whatwg.org/multipage/obsolete.html#attr-table-summary) attribute, and the user agent has not classified the table as a layout table, the user agent may report the contents of that attribute to the user.

Honestly, the only reason I mention the potential for a layout table is to try to find any sort of reason that the HTML standard does not require the table be named.  I was effectively searching for a reason.  The world would be a much better place without layout tables.  But if you feel that we should discard the reality of layout tables then you should push for a change to the HTML spec.   Data tables need names to be useful.  Forcing users to explore rows and columns of data to understand the purpose of a table isn't a practice that ARIA should.  
The question about lists sounds like a separate issue.

**Comment by scottaohara** [comment]
ARIA has specifically gone beyond the requirements of HTML in a few instances which have made this odd mismatch.

tables being one, dialogs, progressbar, listbox (when a popup - you can't even actually name listbox popups at all with native html, just the invoking combobox).

I tend to agree with the practice of providing these all names the majority of time.  there are instances where I also think the purpose of these elements can easily be inferred by other content of the page...  For instance, a table that is the primary content of a web app, where the title of the web page and the heading that precedes the table both provide context to what the tabular data represents.... naming that table adds absolute clarity.  But is it required?  I have a harder time agreeing 100% with the 'requirement' in these cases.

Maybe the issue here is to better indicate "why" names are required.  Because we have talked about this on WG calls before.  We've provided reasoning to each other.  But it is not communicated in the spec in a way that mitigates questions like this coming up.  Why does ARIA require naming when the host language doesn't - while also telling authors they SHOULD use the host language feature which doesn't require naming.

**Comment by JAWS-test** [comment]
I support the suggestion that for elements that don't need a name in HTML but do in ARIA, explain why

**Comment by WilcoFiers** [comment]
Was about to open an issue on this:

> tables being one, dialogs, progressbar, listbox (when a popup - you can't even actually name listbox popups at all with native html, just the invoking combobox).

ARIA itself has an example of a listbox without a name on the combobox section:

```html
<ul role="listbox" id="popup_listbox">
  <li role="option">Zebra</li>
  <li role="option" id="selected_option">Zoom</li>
</ul>
```

**Comment by jnurthen** [comment]
I think the why has been answered - because it helps users in the majority of cases and even in the cases where it is not necessary it doesn't really cause any harm.

Does this need to remain open? If it does someone needs to take ownership and propose specific changes to the spec. I will close it - if anyone objects please reopen.

**Comment by Wildebrew** [comment]
I can see how all interactive elements should have an accessible name, users often navigate between them with the tab key, without exploring the static content in-between. They can also bring up most common interactive element types in a "navigate by element" screen reader lists (using screen reader keys + an f key, usually 5f5, f6 or f7).



To my mind, non-focusable elements are another matter.
Tables, for instance, are not even offered in the "navigate by element" options of either Jaws or NVDA (the only static elements are offered are landmarks and headings, and some landmarks do not require an accessible name).
I've never quite seen the argument for a modal dialog requiring an accessible name. When you click the trigger to display the dialog all non-dialog page content is hidden from the user so the context (that the user is in a dialog) is pretty clear. Most dialogs start with a heading, assigning that heading as the accessible name for the dialog only results in screen readers reading it twice.
Dialogs displayed without a visible title are an equally vexing experience to all users alike.

Dialogs that are displayed without user initiation (primarily session timeout or warning dialogs) would benefit from an accessible name, but if they have a heading at the top they effectively have it, only not programmatically.

Again, back to tables. A user needs to explore a table by navigating between the cells. Most webpages hvae a single, or at most 2 tables, so an accessible name is of limited benefit.
I'm not saying it shouldn't be encouraged, but I'd stop short at making it required.
