### ISSUE TITLE
In Chromium/WebKit, setting ARIA reflected properties to undefined behaves the same as null

### ISSUE THREAD

**Issue by nolanlawson** [w3c/aria#1858]
# Describe your concern

In the spec, there are a few notes about how to treat falsy values for ARIA reflection:

[Getting](https://w3c.github.io/aria/#idl-reflection-attribute-values):

> On getting, a missing ARIA attribute will return `null`.

[Setting](https://w3c.github.io/aria/#enumerated-attribute-values-html):

> On setting, if the new value is `null`, the content attribute must be removed […]

However, this is not how Chromium/Webkit actually behave. In these browsers, setting the value to `undefined` is treated the same as `null` – i.e. it removes the attribute. (In my testing, no other falsy values behave this way – e.g. `0`, `false`, or the empty string.)

Here is [a CodePen to demonstrate](https://codepen.io/nolanlawson-the-selector/pen/vYaezew). Chrome 108 and Safari 16.2 behave identically. In short:

```js
const div = document.createElement('div')

console.log(div.getAttribute('aria-label')) // null
console.log(div.ariaLabel) // null

div.ariaLabel = 'foo'
div.ariaLabel = undefined

console.log(div.getAttribute('aria-label')) // null
console.log(div.ariaLabel) // null
``` 

Firefox 109, with the `accessibility.ARIAReflection.enabled` flag set to `true`, actually behaves differently.

In the initial state, it gives:

```js
console.log(div.getAttribute('aria-label')) // null
console.log(div.ariaLabel) // "" (empty string) <-- this is different
```

And after setting the prop to `undefined`, it gives:

```js
console.log(div.getAttribute('aria-label')) // "undefined" <-- this is different
console.log(div.ariaLabel) // "undefined" <-- this is different
```

(Note this is literally the string `"undefined"`.)

Also note that repeating the experiment [with `null` instead of `undefined`](https://codepen.io/nolanlawson-the-selector/pen/wvxrEmG) gives the same effect in Chromium/Safari. In Firefox (with the flag) it also behaves the same – except with the string `"null"` instead of the string `"undefined"`.

Related issue: https://github.com/w3c/aria/issues/1110

# Link to the version of the specification or documentation you were looking at at.

_Link to documentation:_ https://w3c.github.io/aria/#enumerated-attribute-values-html

_Does the issue exists in [the editors draft](https://w3c.github.io/aria/) (the editors draft is the most recent draft of the specification)?_ Yes.

**Comment by jnurthen** [comment]
@nolanlawson do you suggest the spec is incorrect or that the implementations are incorrect?

**Comment by nolanlawson** [comment]
@jnurthen Both approaches seem reasonable to me, although I think the spec wins slightly on purity. `getAttribute()` returns `null` for nonexistent attributes, so treating `null` as a special value makes sense.

That said, updating the spec to allow for `undefined` may be the most pragmatic approach, since the current implementations have been shipping in [Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=844540) and [WebKit](https://bugs.webkit.org/show_bug.cgi?id=184676) for almost 5 years, so changing them may not be web-compatible.

If you'd like, I can file bugs on WebKit/Chromium and see if they consider it web-compatible to match the spec.

**Comment by smhigley** [comment]
Just in terms of author convenience/understanding, I'd +1 allowing people to do `el.ariaLabel = undefined` to nullify it, not set it to the string "undefined". It's also nice to get a null or undefined value when it's not yet set, rather than an empty string.

In essence: it makes the most sense to me as an author to be able to set a nullish value to unset an aria IDL attribute, and get a nullish value back when reading an attribute that is unset.

**Comment by alice** [comment]
I just had a look to see whether the  [HTML spec](https://html.spec.whatwg.org/multipage/common-dom-interfaces.html#reflecting-content-attributes-in-idl-attributes:idl-domstring-4 has anything to say about `undefined` values. TL;DR it doesn't; longer version below.

I think Firefox setting "null" as a string reflection of `null` is pretty clearly a bug.

I honestly don't have a strong opinion on whether supporting `undefined` as well as `null` for setters makes sense. I think conceptually `null` makes a bit more sense, since we aren't trying to delete the property off the DOM object, but just revert it to a baseline state. 

It might be a bit surprising to set it to `undefined` but get `null` back from the getter, and I can't imagine why we'd try and keep track of whether it was set to `null` or `undefined`, so perhaps there's an argument to be made for not supporting `undefined`, but it's not especially compelling. 

However, I haven't seen any especially compelling arguments for supporting it, either, other than that it's de facto supported already - how might one end up trying to set one of these attributes to `undefined`? Perhaps by getting an unset value off a configuration dictionary? 

So I guess in summary I agree with @nolanlawson in https://github.com/w3c/aria/issues/1858#issuecomment-1396273166 - Chromium/WebKit should probably be updated to be consistent with the spec if it's web-compatible, otherwise the spec should be updated (which would probably be more of a hassle).

---

More on the HTML spec:

It actually has some limitations on using `DOMString?` that I hadn't noticed before:

> If a reflecting IDL attribute has the type [DOMString](https://webidl.spec.whatwg.org/#idl-DOMString)?:
>
> The getter steps are:
>
> [Assert](https://infra.spec.whatwg.org/#assert): the content attribute is an [enumerated attribute](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#enumerated-attribute).
>
> [Assert](https://infra.spec.whatwg.org/#assert): the IDL attribute is [limited to only known values](https://html.spec.whatwg.org/multipage/common-dom-interfaces.html#limited-to-only-known-values).
>
> [Assert](https://infra.spec.whatwg.org/#assert): the content attribute is in some state.
>
> If the content attribute is in a state with no associated keyword value, then return null.
>
> Return the [canonical keyword](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#canonical-keyword) for the state of the content attribute.
>
> The setter steps are:
>
> If the given value is null, then remove the content attribute.
>
> Otherwise, set the content attribute's value to the given value.

It seems like the assertions there don't apply to something like `aria-label`, so they should maybe be moved into an if block as part of this work.

**Comment by nolanlawson** [comment]
@alice Thanks for the review! I filed a bug [on Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1411465) and [on WebKit](https://bugs.webkit.org/show_bug.cgi?id=251383).

I like @smhigley's [comment](https://github.com/w3c/aria/issues/1858#issuecomment-1397407453) about [nullishness](https://developer.mozilla.org/en-US/docs/Glossary/Nullish) – this actually makes the existing behavior more logical to me. But I also agree that the strongest argument in favor of the current de-facto behavior is just web compatibility. I'll be interested to see if Chromium/WebKit folks think this is a web-compatible change.

**Comment by nolanlawson** [comment]
Follow-up from AOM meeting: if we're going to codify this behavior in the spec, the spec should specify that, when you set to `undefined`, the getter returns `null` afterwards (i.e. it doesn't "remember" a distinction between null and undefined).

**Comment by nolanlawson** [comment]
Per https://github.com/w3c/aria/pull/2057#discussion_r1372127984 there is actually no issue with the spec – it is just inherent to [nullable types](https://webidl.spec.whatwg.org/#es-nullable-type) that `undefined`/`null` behave this way. 

The browser implementations are also all in alignment as of Firefox 119, so I've proposed closing the [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1411465), and I've closed [the WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=251383).

I also opened a PR on WPT to confirm the `undefined`/`null` behavior: https://github.com/web-platform-tests/wpt/pull/42748
