### ISSUE TITLE
ARIAMixin element-reflecting IDL attribute names

### ISSUE THREAD

**Issue by annevk** [w3c/aria#1878]
This is probably too late to change now, but I wanted to raise it for the future at the least. The element-reflecting IDL attributes are all suffixed with "Element" or "Elements". That's not how we tend to name reflecting IDL attributes.

Can we use the name without a type suffix from for new additions? Can we fix the existing names still?

cc @rniwa @cookiecrook @mrego

**Comment by alice** [comment]
That was an explicit choice, since element reflection isn't (yet) used anywhere else. We were also considering having reflection to both string (IDREF) *and* element IDL attributes, but decided that was going to be too confusing to use for extremely marginal benefit over `setAttribute()` given there was already the element reflection option.

**Comment by annevk** [comment]
@domenic mentioned that we could maybe use this convention to retrofit some existing ID IDL attributes to have element-reflecting counterparts.

Not the biggest fan of names that include the type, but perhaps for these it's okay then.

**Comment by annevk** [comment]
I see that the new popover feature also uses this naming style. I'll create a PR to document that in HTML.
