### ISSUE TITLE
Possible discrepancy with aria-required and inherited child widget roles.

### ISSUE THREAD

**Issue by accdc** [w3c/aria#2024]
Filing this to get on the agenda.

According to:
https://w3c.github.io/aria/#aria-required

Within the “Used in Roles” list, it states role=radiogroup as supported. The result being that using aria-required=”true” on role=radiogroup will cause all child radios to be flagged as required.

Since role=radiogroup is implicitly mapped to fieldset, and role=group maps to the same, should role=group be added to this list?

**Comment by scottaohara** [comment]
radiogroup is not mapped to fieldset/group.  there are variations in the mappings.

**Comment by accdc** [comment]
I understand, I was actually referring to the table at:
https://www.w3.org/TR/html-aria/
View fieldset.

**Comment by scottaohara** [comment]
That spec doesn’t say radiogroup is mapped to fieldset.  It says group is mapped to fieldset (which is an informative reference to html aam) and that radiogroup is a role that authors can specify on fieldset.

**Comment by accdc** [comment]
Granted, but what should happen in this case?

```
<div role="group" aria-required="true" aria-label="Personal Information">
<input title="First Name" >
<input title="Last Name" >
</div>
```

When you run this example and examine the accessibility tree, how is it different from the following?

```
<div role="radiogroup" aria-required="true" aria-label="Personal Information">
<div role="radio" tabindex="0">Home Address</div>
<div role="radio" tabindex="-1">Shipping Address</div>
</div>
```

The required state is not present in either one when viewed in Chrome, however when using JAWS both examples say that all of the above fields are required.

So, what is the expected behavior and how is this reflected in the ARIA spec?

**Comment by scottaohara** [comment]
when i looked at this in the a11y tree 'required' was specifically called out for the radiogroup, but not for the group. 

that makes sense, since a radio group is a set of radio buttons where it is meant to represent a single choice within the radio grouping of choices.  For a group, that's not the case.  Heck, a group doesn't even need to contain form controls.  

Further testing shows that this doesn't do the same thing as if you were to put the required state on the actual inputs.  

E.g., with 
```
<div role="group" aria-required="true" aria-label="Personal Information">
<input title="First Name" >
<input title="Last Name" >
</div>
```

the required state is announced at the 'group' level and it is not consistently announced depending on how you navigate to the different inputs, since it's not actually exposed on the inputs.

but with the following
```
<div role="group"aria-label="Personal Information">
<input title="First Name"  aria-required="true" >
<input title="Last Name" aria-required="true"  >
</div>
```

the required state is exposed / announced for each input, as it should be.

To me, the fact that 'required' is exposed on group is odd, and doesn't jive with the fact you can't make a fieldset required with html alone.  Adrian Roselli did a study that touched on this back in 2022 - https://adrianroselli.com/2022/02/support-for-marking-radio-buttons-required-invalid.html

I would rather required _not_ be announced on group since it's not listed as a supported attribute, nor has it been in the past,. 
 The idea doesn't make a lot of sense since a group can contain a number of controls / content / no controls at all, and it doesn't actually pass the state down to the individual elements, but rather keeps it at the container level - so one gets inconsistent behaviors if looking for required fields.

shrug?

**Comment by accdc** [comment]
Thanks, that makes sense to me. It was confusing which is why I opened this, but it seems clearer to me why it's not included.

Which tool are you using to examine the accessibility tree? I was looking at the MSAA object tree but that may not be the best to do so.
