### ISSUE TITLE
Clarification of Combobox Role and aria-haspopup Attribute Requirements

### ISSUE THREAD

**Issue by LaurenceRLewis** [w3c/aria#2132]
# Describe the change
The current specification text has two separate paragraphs describing the aria-haspopup attribute value requirements on a combobox—which are essentially the same. These have a conflict on the MUST use of aria-haspopup that pops up a Listbox. The proposed amendment aims to merge these paragraphs to enhance clarity, ensuring a clear understanding between the role combobox and the aria-haspopup values.

Current wording in the specification.

> "Authors MUST ensure the popup element associated with a combobox has a role of listbox, tree, grid, or dialog." 

Followed by the paragraph;

> "Elements with the role combobox have an implicit aria-haspopup value of listbox. If the combobox popup element has a role other than listbox, authors MUST specify a value for aria-haspopup that corresponds to the role of its popup."

These two paragraphs should be combined for clarity  and rewritten as;

"Elements with the role combobox have an implicit aria-haspopup value of listbox. If the combobox popup element has a role other than listbox, authors MUST specify a value, tree, grid, or dialog, for aria-haspopup that corresponds to the role of its popup."

Link to documentation: [WAI-ARIA 1.2 Combobox](https://www.w3.org/TR/wai-aria-1.2/#combobox)

The issue also exists in the editor's draft: [W3C Editor's Draft - Combobox](https://w3c.github.io/aria/#combobox)

**Comment by KateZhaoTR** [comment]
I think this change would be helpful, the only edit I would suggest is very minor: "...authors MUST specify a value **of** tree, grid, or dialog..."

**Comment by scottaohara** [comment]
Reading through this a few times and it seems like it'd be a good editorial change, with Kate's suggestion.  Care to make a PR, @LaurenceRLewis ?

**Comment by TalyahAtUXAccess** [comment]
By standard behavior, assistive technology users expect that when interacting with a combobox, pressing the down arrow key will move focus into the associated popup or listbox that opens as part of the combobox control. This predictable interaction is essential for effective keyboard navigation.

For this reason, it is unclear how a combobox could open a dialog instead of a listbox or similar popup. A dialog typically exists outside the immediate DOM structure, often rendered at the end of the DOM or in a different container. This raises a concern: how would the down arrow key move focus into the dialog? Such an implementation could break expected navigation patterns mainly for screen reader users.

**Comment by scottaohara** [comment]
Not if the developer properly manages focus. 

Many custom combobox implementations have their popup located at the bottom of the dom. That shouldn’t be as necessary anymore if they were to use the popover attribute… but it’s not really an issue if the popup (listbox or dialog, etc) have been authored with the expected keyboard commands. 

All that said, this is a bit off topic to what this closed issue was covering. Is this maybe a new topic of discussion that would make sense over on the aria practices GitHub issues?  The aria spec doesn’t really get into the specifics of keyboard behaviors since they can vary depending on the platform.
