### ISSUE TITLE
Prettier throws errors on PRs opened from forks

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria#2294]
See: https://github.com/w3c/aria/pull/2290

**Comment by pkra** [comment]
This appears to be a limitation of github actions (of this type) according to https://github.com/creyD/prettier_action/issues/54#issuecomment-858891671 (and the link from there).

**Comment by spectranaut** [comment]
Do we need some kind of requirement for people who open PRs against ARIA from different repos to run prettier locally on their branch?

**Comment by smockle** [comment]
I ran into this too, in https://github.com/w3c/aria/pull/2271#issuecomment-2228598838.

The error is happening in the checkout step (not the prettier step), because `github.head_ref` ([.github/workflows/prettier.yaml#L19](https://github.com/w3c/aria/blob/4f38467c43d20803b09b0d33284cb28f34176932/.github/workflows/prettier.yaml#L19)) is the fork’s branch name, which won’t exist in _this_ repo.

We could revise the checkout step like this—
```YAML
uses: actions/checkout@v4
with:
  ref: ${{github.event.pull_request.head.ref}}
  repository: ${{github.event.pull_request.head.repo.full_name}}
  fetch-depth: 0
```

—that’d get us further, but we’d hit another problem: permissions. The default token used in w3c/aria’s workflows doesn’t have permissions to write (i.e. push commits) to random other repos (even forks).

There’s a two-part solution to that:

1. The fork’s owner (presumably, the PR author) needs to [“allow edits and access to secrets by maintainers”](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests).[^1]

2. We need to run the workflow using a bot account’s token, and that bot account needs to have [“Write” access](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization) to this repo.

[^1]: Optionally, we can add a comment to PRs if the author hasn’t done this. Homebrew does this, via [.github/workflows/publish-commit-bottles.yml#L45-L47](https://github.com/Homebrew/homebrew-core/blob/d68a4ae2ba878edc12c0369e398a5f00c8bbd2a4/.github/workflows/publish-commit-bottles.yml#L45-L47).

**Comment by daniel-montalvo** [comment]
Thanks much @smockle for your detailed explanation.
I'll take a look at this.

I would prefer for The fork’s owner (presumably, the PR author) to “allow edits and access to secrets by maintainers”. We don't currently have a bot account set up.
