### ISSUE TITLE
[AriaNotify] Speech markup/pronunciations (i.e. SSML or IPA)

### ISSUE THREAD

**Issue by alisonmaher** [w3c/aria#2335]
As discussed in https://github.com/w3c/aria/discussions/1958#discussioncomment-6223153, there may be cases where an author would want to provide a separate string to provide a hint to ATs for how the notification should be spoken.

The use cases provided in the discussion thread are compelling, and I think there is value to such an addition. However, I would like to propose that we consider this for a future version of the API instead to allow us to gather feedback from developers and end users as `ariaNotify` starts to get adopted with its current set of functionality. This will help inform the best way to incorporate this additional customizability going forward.

**Comment by jcsteh** [comment]
It's worth noting that practically speaking, we don't have any mainstream, interoperable way to specify speech markup or pronunciation anywhere else in HTML, ARIA or CSS. There is ongoing work in this area, but it hasn't yet resulted in any mainstream implementations. It seems like perhaps that problem needs to be solved properly before we try to solve this specifically for notifications. Otherwise, we might end up with diverging ways of specifying speech markup/pronunciation and that certainly wouldn't be ideal.

**Comment by alisonmaher** [comment]
This was also discussed at TPAC:

> keithamus: there are a couple open issues I can lump together that I think we can defer. But I think braille support and speech markup we can design around those later

The group seemed to agree with deferring this till a future version

**Comment by minorninth** [comment]
> It's worth noting that practically speaking, we don't have any mainstream, interoperable way to specify speech markup or pronunciation anywhere else in HTML, ARIA or CSS.

While we don't have a general-purpose way to specify all of the speech markup we do want, there are a number of things in HTML and CSS that some screen readers do consume that affect pronunciation:

- The lang attribute
- CSS speak-as
- aria-braillelabel
- The <abbr> element
- The <pre> element
- <input type="tel">

I completely agree we need a lot more! But my hope would be that as we add more ways to specify speech markup or pronunciation in HTML, we could build on those in ariaNotify rather than needing to reinvent them
