### ISSUE TITLE
HTML-AAM: missing section ids in Name and Description Calculation

### ISSUE THREAD

**Issue by cyns** [w3c/aria#253]
In the re-written (and much better!) name and description caluculation section, the sections don't have IDs for deep links.  For example, this link doesn't take you directly to the section on placeholder https://rawgit.com/w3c/aria/master/html-aam/html-aam.html#h-input-type-text-input-type-password-input-type-search-input-type-tel-input-type-email-input-type-url-and-textarea-element-accessible-name-calculation

**Comment by jasonkiss** [comment]
Wondering if this had to with the mixed content blocking performed by web browsers these days: the link to the "respec-w3c-common" script from the document's `<head>` used http, so it was getting blocked since the page link you provide requested https. As a result, respec wasn't loading, and the IDs weren't getting created on section headings, so any links to those fragIDs wouldn't work. 

See commit 89d1819e88efb8f74335a323a16fd0b5b83ef542. I've changed the link to that script to use https, and now respec loads, and the page (eventually) takes you directly to section 5.1.1 input type="text", input type="password", input type="search", input type="tel", input type="email", input type="url" and textarea Element Accessible Name Calculation.

Is this now the behaviour you were expecting?

**Comment by cyns** [comment]
That works. Thanks.
