### ISSUE TITLE
[DPub] Possible issues with role superclasses

### ISSUE THREAD

**Issue by Joanmarie** [w3c/aria#278]
I was looking at the role definitions in the [DPub ARIA role definitions](https://rawgit.com/w3c/aria/master/aria/dpub.html#role_definitions) as part of identifying mappings for my platform. I question some of the superclasses and would like confirmation that the current superclasses are correct.

From the [Core ARIA role definitions](https://rawgit.com/w3c/aria/master/aria/aria.html#role_definitions):

* `Group`: "A **set** of user interface objects which are not intended to be included in a page summary or table of contents by assistive technologies." (emphasis added)
* `Section`: "A renderable structural containment unit in a document or application."
* `None`: "An element whose implicit native role semantics will not be mapped to the accessibility API."

With the above in mind:

These roles strike me as _not_ a set, but have `group` as their superclass:
* `doc-abstract`
* `doc-colophon`
* `doc-credit`
* `doc-dedication`
* `doc-epigraph`
* `doc-example`
* `doc-footnote`

This role _does_ strike me as a set, but has `section` as its superclass:
* `doc-part`

These roles strike me as something whose implicit native role semantics _should_ be mapped to the accessibility API, but have `none as their superclass:
* `doc-cover`
* `doc-pullquote`

Also:
* `doc-endnote` subclasses `listitem` (which seems appropriate). BUT if an author did not use an (un)ordered list element, but, say, a `div`, then ATs would have accessible list items outside of an accessible list. And that's broken. I think it might be worth adding a statement that `doc-ednote` MUST be a child of a list (`ul`, `ol`) element or of an element with the `list` role.
* `doc-footnote` does not subclass list item. This strikes me, admittedly a non-publishing-industry person, as oddly inconsistent with `doc-endnote`'s superclass. So I figured I'd ask as long as I was here.

Thanks!

**Comment by Joanmarie** [comment]
@TzviyaSiegman or @mattgarrish or @mgylling: Explicit ping so it doesn't get lost in the ARIA github spam. :)

**Comment by mattgarrish** [comment]
The superclasses are on our list of things to review, including whether all the current landmarks need to be landmarks. But it definitely looks like all the current "group" subclasses got linked up wrong. They look like they should inherit from "section" directly and avoid the interface object grouping aspect.

And, yes, not requiring endnote be in a list is an oversight. The restriction is only mentioned in endnotes.

The reason for endnote/footnote having different superclasses is to account for notes that are not grouped. A traditional footnote occurs at the bottom of the page where it is referenced rather than the and of the section/book. Some publishers still intersperse these notes in the body of the text rather than group them at the end. If we used listitem exclusively, then they'd need to put a list around each individual note wherever it occurs.

**Comment by TzviyaSiegman** [comment]
Issues resolved
