### ISSUE TITLE
HTML-AAM: select element should map to listbox role regardless of presentation

### ISSUE THREAD

**Issue by mcking65** [w3c/aria#359]
The html AAM maps the select element differently based on the size and multiple selection values.

This seems like using role to describe presentation rather than interaction model.

HTML select has the interaction model of a listbox regardless of the value of size. 

ARIA combo is defined as a composite that includes a textbox and a separate popup element. HTML select does not include a textbox that instantiates a separate popup element.

In the APG, when describing how to build a custom element that is a single-select list, it seems strange that we would tell authors to use combobox when presenting the widget one way and listbox when presenting it another, even if both presentations have the same interaction model.

I propose that HTML select should always map to listbox.

**Comment by asurkov** [comment]
You're not arguing for having both combobox and listbox roles, right?

On semantic level HTML:select is a combobox widget, and HTML:select@size>1 is a listbox widget. At least I'm not sure I follow "interaction model" argument, because HTML:select looks and behaves like a combobox. On API level the browser exposes these widgets (presentations) differently too, for example, it creates different accessible trees for them.

Also this is definitely a legacy issue, and the proposed changes are not backward compatible.

**Comment by jasonkiss** [comment]
This issue was moved to w3c/html-aam#46
