### ISSUE TITLE
<dl> role should = list

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/aria#371]
suggest changing dl ARIA mapping to list, from 'no corresponding role' http://w3c.github.io/aria/html-aam/html-aam.html#el-dl

**Comment by jasonkiss** [comment]
If we map `dl` to `list`, then it implies a formal semantic and default API mappings for `dl` that don't readily account for its greater complexity of the specific mappings that ATK and AX already have for lists of name-value groupings. 

ATK has `ROLE_DESCRIPTION_LIST`, `ROLE_DESCRIPTION_TERM`, and `ROLE_DESCRIPTION_VALUE` expressly for name-value groupings. These would seem to be the preferred ATK mappings for `dl`, `dt`, and `dd`, respectively. But they are are not the default mappings for the `list` role.

And while AX maps `dl` to the `AXList` role, it additionally takes an `AXDefinitionList` subrole  in Chrome (as the HTML-AAM currently recommends), while `dd` gets the `AXDefinition` subrole. Meanwhile, Safari uses `AXList` with the `AXDescriptionList` subrole for `dl`, and the `AXDescription` subrole for `dd`. Safari keeps the `AXDefinition` subrole for the `dfn` element. Safari's AX approach is closer to the way that ATK has it, and more in line with how the HTML spec defines `dl`, `dt` and `dd`. In both Chrome and Safari, the `dt` element is mapped to `AXGroup` with an `AXTerm` subrole. 

If `dl` is mapped to `list`, its children need to be either `listitem` or `group` roles. If `dt` is mapped to `listitem`, then what of `dd`? The `group` role is seemingly inapplicable since the `dd` will not itself contain `listitem`s. So `dd` must also map to `listitem`. 

Maybe UAs could produce an explicit structure in the accessibility tree for the implied `group` containing each name-value grouping, something along the following lines?

```
<dl role="list">
	<implied role="group">
		<dt role="listitem">
		<dd role="listitem">
	</implied>
	<implied role="group">
		<dt role="listitem">
		<dd role="listitem">
	</implied>
</dl>
```

Or maybe, to better support lists of name-value groupings (instead of flat lists like `ul` or `ol`), ARIA needs a few more roles, like "descriptionlist" and "descriptionvalue" for `dl` and `dd`, respectively? And if `term` can't get redefined to support both `dt` and `dfn`, then maybe also "descriptionitem" for `dt`?

**Comment by jasonkiss** [comment]
This issue was moved to w3c/html-aam#51
