### ISSUE TITLE
Confusing notation in definition of attributes introduced in ARIA 1.1

### ISSUE THREAD

**Issue by LJWatson** [w3c/aria#406]
The definition for the <a href="https://www.w3.org/TR/2016/WD-wai-aria-1.1-20160317/#aria-current">aria-current</a> attribute opens with:
"[ARIA 1.1] Indicates the..."

Assume this should display the attribute name?

**Comment by Joanmarie** [comment]
I'm afraid I don't understand. The current short definition is "Indicates the element that represents the current item within a container or set of related elements." (The "[ARIA 1.1]" notation is there as an indication that this attribute was introduced in ARIA 1.1)

Could you please provide a new short definition that corrects the typo you're reporting? Thanks and sorry for my being dense.

**Comment by LJWatson** [comment]
Thanks for the explanation Joannie. When reading the spec (especially with a screen reader), that isn't at all clear. It effectively reads as "ARIA 1.1 indicates...".

Could I suggest putting the ARIA 1.1 notation on a separate line, or separating it from the definition text in some way?

Actually, I should ask why we're calling out attributes introduced in 1.1? Is the expectation that this notation will remain when the spec reaches Rec? If so, I don't think it's something other specs tend to do.

**Comment by Joanmarie** [comment]
Aha. Thanks for the clarification. I've updated the summary further because it's not just aria-current; it's all the newly-introduced properties.

As for why. James Craig started it and the rest of us have continued it. I'm not sure who all is using the notation. It's helpful for group members to quickly locate what we need to test as part of the exit criteria. Implementors might use it to quickly locate new and modified attributes.

Whether or not those indicators should be removed before the spec reaches Rec is something the group should discuss. Making them more screen-reader friendly is something we should do. Would you mind raising this issue on the ARIA mailing list? (Yes, we do have too many channels of communication. But I believe more members read the list than follow github issue discussions.)

**Comment by MichielBijl** [comment]
This meta data right? So could it be in a comment? Or a note if you want to keep it on the front of the doc. Last line of the section could read:

> aria-current (or whichever attribute) was introduced in ARIA 1.1.

Short and sweet :)

**Comment by joanmarie** [comment]
Indicators removed. Closing.
