### ISSUE TITLE
Typo in ARIA 1.1 Authoring Guide

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria#431]
https://rawgit.com/w3c/aria/master/practices/aria-practices.html
"Sometimes trees (and other lists or grids) cannot be completed represented in the DOM due to performance limitations of the browser."

"completed represented" should probably be "completely represented".

**Comment by mcking65** [comment]
@carmacleod,

The APG was split into its own repo (w3c/aria-practices). The editors draft is at:
http://w3c.github.io/aria-practices/

I do not find this phrase in the latest editors' draft.

**Comment by carmacleod** [comment]
Wow, they're really different. I thought the rawgit one must be the latest because the date at the top of the doc is 08 September 2016, and the date at the top of the github version is 01 September 2016.
Is the rawgit version being generated every day from old code?

**Comment by mcking65** [comment]
Carolyn, the date you see at the top is the date that the respec javascript was run. When viewing in rawgit, it is run real time. when you view on github.io, the date you see is the last time the document was pushed to gh-pages. In the new aria-practices repo, we are pushing to gh-pages automatically each time we push to master. That was last done on Sep 1.

Yes, the documents are now very different.

If you are interested in what is coming for APG 1.1 to replace content that was removed because it needed lots of work to meet the current APG editorial guidelines, was out-of-date, or contained substantive inaccuracies, I encourage you to review the APG 1.1 milestone plan:
https://github.com/w3c/aria-practices/milestones

**Comment by carmacleod** [comment]
Thanks, Matt. That explains things.  :)
Thanks also for pointing out the milestones link. Much appreciated!
