### ISSUE TITLE
CORE-AAM 1.1: Add mappings for aria-errormessage on macOS

### ISSUE THREAD

**Issue by richschwer** [w3c/aria#457]
Moved from this action in tracker: https://www.w3.org/WAI/ARIA/track/actions/2119

**Comment by cookiecrook** [comment]
https://bugs.webkit.org/show_bug.cgi?id=165190

**Comment by joanmarie** [comment]
Whether or not it's implemented in WebKit/Safari, we need mappings for this ARIA feature stated in the Core AAM. Hence the summary/title change.

**Comment by joanmarie** [comment]
@cookiecrook: As I mentioned in pull request #620, we really need to wrap up these remaining issues. If you could provide the language we should add to the Core AAM for macOS, that would be great. Thanks!

**Comment by cookiecrook** [comment]
I don't have the answers at the moment. I'd like to cast my vote (again) that the AAM documents be Living standards rather than Rec track.

**Comment by joanmarie** [comment]
> I'd like to cast my vote (again) that the AAM documents be Living standards rather than Rec track.

That -- or at least something closer to that -- has my vote too: Platform accessibility APIs change at a different rate (often a much more timely rate) than W3C standards. Thus the "correct" mappings (as far as the W3C is concerned) are in danger of becoming incorrect as far as platform accessibility APIs and ATs are concerned.

But **_with respect to the 1.1 cycle_**, I'm afraid going the living standard route is not possible. Not only is Core AAM 1.1 behind with respect to the milestones established for it, but ARIA 1.1 currently depends on Core AAM 1.1. And because of that, the ARIA spec's progress along the REC track is blocked.

Therefore, anything you/Apple can do to help us get Core AAM 1.1 moving on its current REC track would be greatly appreciated. During the 1.2 cycle let's see what we can do to get the mapping specs closer to being living standards -- along with trying to decouple ARIA from the Core AAM insofar as the REC track is concerned so that we don't find ourselves in this sort of bind again.

**Comment by cookiecrook** [comment]
We are discussing a new property and notification name internally, but I don't have an answer for you yet. I'll confirm in the next few days if there are no objections.

**Comment by cookiecrook** [comment]
Resolved by latest commit to PR #620
