### ISSUE TITLE
CORE-AAM 1.1: Create macOS Mappings for aria-colindex, -rowindex, -colcount, -rowcount

### ISSUE THREAD

**Issue by richschwer** [w3c/aria#459]
Moved from this action in tracker: https://www.w3.org/WAI/ARIA/track/actions/2119

**Comment by richschwer** [comment]
Note: one issue we are discussing with NVDA and Freedom Scientific is the issue of dealing with aria-colindex and aria-rowindex, aria-rowspan, aria-colspan in the mappings when rows or columns are discontinuous.

**Comment by cookiecrook** [comment]
What does that mean? rowspan and colspan by definition make the spanned columns discontiguous don't they?

**Comment by cookiecrook** [comment]
These are mapped to: AXARIAColumnIndex, AXARIARowIndex, AXARIAColumnCount, AXARIARowCount. The *span attrs change the row/col associations.

**Comment by klown** [comment]
Thanks @cookiecrook 

> These are mapped to: AXARIAColumnIndex, AXARIARowIndex, AXARIAColumnCount, AXARIARowCount. 

There are macOS mappiings of [aria-rowindex](https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#ariaRowIndex) and [aria-colindex](https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#ariaColIndex). I suspect these are wrong, but I wanted to confirm it with you:
`AXRowIndexRange: loc=<rowindex value> len=<rowspan value>`
`AXColumnIndexRange: loc=<column index value> len=<colspan value>`


>The *span attrs change the row/col associations.

I don't know how to word that in the mapping table.  What should go in the AX API cell for [aria-rowspan](https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#ariaRowSpan) and [aria-colspan](https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#ariaColSpan)?  Note, again, there already are entries:
`AXRowIndexRange: loc=<rowindex value> len=<rowspan value> `
`AXColumnIndexRange: loc=<column index> len=<colspan value> `

**Comment by Joanmarie** [comment]
For the sake of documentation, etc.:
* [Nan did the implementation in October 2015](https://trac.webkit.org/changeset/190833).
* From that commit, there is a new [layout test](https://trac.webkit.org/browser/trunk/LayoutTests/accessibility/mac/aria-table-attributes.html?rev=190833#L1) which covers (and indirectly shows mappings for) the new attributes.  Here are the [Mac port's expectations](https://trac.webkit.org/browser/trunk/LayoutTests/accessibility/mac/aria-table-attributes-expected.txt?rev=190833#L6). They confirm what [James stated above](https://github.com/w3c/aria/issues/459#issuecomment-266966374), namely:
    * `aria-colcount` is mapped to `AXARIAColumnCount`
    * `aria-rowcount` is mapped to `AXARIARowCount`
    * `aria-colindex` is mapped to `AXARIAColumnIndex`
    * `aria-rowindex` is mapped to `AXARIARowIndex`

Regarding the mappings for spans, that's slightly harder to pull out of the layout test due to how tests are written. But the Layout Test expectations related to ranges and cells with spans > 1 can be seen starting at [line 13](https://trac.webkit.org/browser/trunk/LayoutTests/accessibility/mac/aria-table-attributes-expected.txt?rev=190833#L13). The values of WKTR's `rowIndexRange()` and `columnIndexRange()` on the Mac come from `AccessibilityUIElement::rowIndexRange()` and `AccessibilityUIElement::columnIndexRange()` respectively. And if you look at the [associated code](https://trac.webkit.org/browser/trunk/Tools/WebKitTestRunner/InjectedBundle/mac/AccessibilityUIElementMac.mm#L1315), you'll see the values come from `AXRowIndexRange` and `AXColumIndexRange` respectively. And for each of those, the value is a (`range.location`, `range.length`) pair.

The previous paragraph is a long way of saying that I myself think that what is in the mapping table currently seems correct to me. Mind you, I was a tad surprised by the abbreviations "loc" and "len" because that seems really unWebKitish. But I just built Safari, loaded the test case, and examined it using Accessibility Inspector. It is indeed "loc" and "len". See attached screenshot (which includes nearly all the cell properties, because why not?). Lastly, all this jives with what's in the HTML-AAM for [`colspan`](https://w3c.github.io/html-aam/#att-colspan) and [`rowspan`](https://w3c.github.io/html-aam/#att-rowspan).

And all of the above is a long way of saying: Is there any additional information needed to finalize the mappings in the Core AAM for the specified attributes?

![screen-shot-documenting-cell-property-mapping](https://cloud.githubusercontent.com/assets/3228171/21996803/f2027b2c-dbf9-11e6-9ce7-a364ae361d21.png)

**Comment by cookiecrook** [comment]
@klown wrote:

> `loc=<rowindex value>`

Except these are 0-based to ARIA's 1-based arrays.

@Joanmarie wrote:

> Mind you, I was a tad surprised by the abbreviations "loc" and "len" because that seems really unWebKitish. 

I doubt anyone would object to a dict keyname change if you proposed one.

**Comment by klown** [comment]
Modifications made:
https://github.com/w3c/aria/commit/f4c807710bf1131aa3f460b0719e3aa996dc0f3d

Closing.
