### ISSUE TITLE
Definition of children presentational eroneously states that making presentational is equivalent to hiding all descendants.

### ISSUE THREAD

**Issue by mcking65** [w3c/aria#491]
Section [5.2.8 Presentational Children](http://w3c.github.io/aria/aria/aria.html#childrenArePresentational) 
defines children presentational true as:

> The DOM descendants are presentational. User agents should not expose descendants of this element through the platform accessibility API. 
> If user agents do not hide the descendant nodes, some information may be read twice.

So, it is saying that making something presentational hides all descendant nodes from the accessibility API.

While role none says:

> Many individuals erroneously consider role="presentation" to be synonymous with aria-hidden="true", and we believe role="none" conveys the actual meaning more unambiguously.

And aria-hidden is defined as:

> Indicates whether the element is exposed to an accessibility API. 

These are the same words used to define children presentational true.

I think section 5.2.8 needs to be reworded to state something more like:

> The DOM descendants are presentational. User agents SHOULD expose only the text content of descendants of this element through the platform accessibility API.

**Comment by joanmarie** [comment]
This change appears to be modifying a normative statement. There's also a chance it may impact implementations and presentation by assistive technologies. In particular, the opening report quotes spec text which states "If user agents do not hide the descendant nodes, some information may be read twice." If we make the change proposed, in which we explicitly tell user agents to include the text content, might we be in danger of having screen readers present some information twice? I don't think we can answer that question for certain without some further investigation and testing.

Because of the above (normative statement + may actually impact user experience), I do not think this is an editorial change. Thus I'm going to remove that label. Because normative changes would require exiting and re-entering CR, something the Working Group determined it did not want to do, changes in this area will have to wait until 1.2.

**Comment by jnurthen** [comment]
@mcking65 If you think there is something that needs changing here can you please submit a PR. I'm not convinced there is any change that needs to be made.

**Comment by JAWS-test** [comment]
I think the ticket can be closed because in [ARIA 1.2](https://www.w3.org/TR/wai-aria-1.2/#tree_exclusion) it says correctly:

> However, the text content of any excluded descendants is included.
