### ISSUE TITLE
Potential need for a new CSS pseudo-class for role matching

### ISSUE THREAD

**Issue by therealglazou** [w3c/aria#506]
Testing in CSS an `epub:type` fallback for an absent `role` attribute is a bit cumbersome. Such a selector would be in the form of (for a cell role):

```
[epub|type="cell"]:not([role]) {
   ...
}
```

and it would require a namespace at-rule:

```
@namespace epub "http://www.idpf.org/2007/ops";
```
Maybe a new `:role()` pseudo-class is needed here to ease the pain and deal automagically with that fallback; some UAs could look only at `role` to resolve it while EPUB Agents would also deal with the `epub:type` fallback. Just thinking out loud here.... That would of course require joint work with the CSS WG.

**Comment by AmeliaBR** [comment]
There is definitely a need for an API to access the computed role of an element.  The `role` itself can have fallback values, and values that are dis-allowed because of native semantics, and of course default roles based on semantics.  A CSS pseudo-class has the benefit of exposing this information to both scripts and declarative styling.

**Comment by jnurthen** [comment]
@IanPouncey something for the CSS Accessibility Task Force to consider?

**Comment by jnurthen** [comment]
This issue was moved to w3c/css-a11y#32
