### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria#521]
Roles for HTML [drag and drop](https://www.w3.org/TR/html52/editing.html#drag-and-drop).

Discussion in [2 Feb 2017 ARIA telecon](https://www.w3.org/TR/html52/editing.html#drag-and-drop). Note this is HTML 5.2, not 5.1 like the other HTML parity issues.

**Comment by michael-n-cooper** [comment]
Need to discuss this with Web Components people. @LJWatson to help liaise.

**Comment by cookiecrook** [comment]
If ARIA 1.2 is still limited to HTML Role Parity, this issue is not in scope.

**Comment by mcking65** [comment]
@cookiecrook, that was what I suggested during the meeting. However, the group thought aligning ARIA 1.2 with HTML 5.2 would be most appropriate, which could expand the scope to include drag/drop. I guess 5.2 has some drag/drop related attributes.

**Comment by cookiecrook** [comment]
Complete feature parity with HTML will not happen in a point release. I recommend sticking to the original scope and only accepting "role parity" issues for ARIA 1.2

**Comment by mcking65** [comment]
@cookiecrook, 

I agree that drag/drop is probably too big for 1.2. However, I am wondering Where the 1.2 scope statement is?

**Comment by cookiecrook** [comment]
@michael-n-cooper mentioned this yesterday. @Joanmarie?

**Comment by Joanmarie** [comment]
@cookiecrook: I am not aware of anything definitive and formal (like a "1.2 scope statement"). We have the 1.2 "milestones" and 1.2 "issues" in github and a 1.2 "product" in tracker. Perhaps a set-in-stone "1.2 scope statement" would be useful. Then again, if some low-hanging fruit comes along AND it passes the "high-impact, low-risk" test, it seems like excluding it purely on the basis of it not being in the "scope statement" might not be what we want to do.

All of that being said, ARIA 1.1 deprecates its drag-and-drop attributes but fails to replace them with anything. I'm guessing that's because cross-platform accessible drag-and-drop is not an easy problem to solve. Therefore, I think we should declare drag-and-drop as out of scope for 1.2 on the basis of it being neither role parity nor high-impact, low-risk, low-hanging fruit.

**Comment by spectranaut** [comment]
closed during issue triage in this meeting: https://www.w3.org/2024/05/30-aria-minutes.html#t08
