### ISSUE TITLE
DPUB glossdef/glossterm not necessary for accessibility. 

### ISSUE THREAD

**Issue by cookiecrook** [w3c/aria#55]
DPUB glossdef/glossterm and bibliodef/biblioterm should use same general roles as HTML `<dt>` and `<dd>`. Note that these do not yet have a 1:1 mapping between HTML 5 and ARIA 1.1, so we'll need roles added to the core ARIA spec.

**Comment by cookiecrook** [comment]
But in the meantime, EPUB and other technologies can just use the native HTML elements.

**Comment by cookiecrook** [comment]
Removing biblio from this issue since that is not a paired list.

**Comment by TzviyaSiegman** [comment]
We included these set of terms (glossterm/def) because not all glossaries
are standalone components. it is quite common in a textbook setting, for
example, to list the glossary term in a chapter (perhaps as a bolded term)
and the glossary definition as linked text. In the print world, the term
might be defined in the margin or in a glossary section at the end of the
chapter or book. In digital, the definition can be provided as a pop-up, in
floating box near the glossterm. <dl> is not always the right context.

**Comment by cookiecrook** [comment]
If there is an inline widget for viewing definitions, it should be exposed as a widget such as a popup button.

**Comment by TzviyaSiegman** [comment]
Thank you for your feedback. This issue has been resolved by editing the document to comply with the rules for extending ARIA (https://www.w3.org/WAI/PF/wiki/ARIAExtensions).
