### ISSUE TITLE
Unnecessary and misleading role="tree" logic for role="row" mapping

### ISSUE THREAD

**Issue by aleventhal** [w3c/aria#554]
The ARIA spec allows the following containers for row:
grid, rowgroup, table, treegrid

However, CORE-AAM contains the following text for row:
ROLE_SYSTEM_ROW unless inside a tree or treegrid, in which case ROLE_SYSTEM_OUTLINEITEM

This text leads one to believe that a tree can contain a row, but it cannot.

**Comment by mcking65** [comment]
@klown,  should:

> ROLE_SYSTEM_ROW unless inside a tree or treegrid, in which case ROLE_SYSTEM_OUTLINEITEM

be changed to:

> ROLE_SYSTEM_ROW unless inside a treegrid, in which case ROLE_SYSTEM_OUTLINEITEM

Or should it be:

> ROLE_SYSTEM_ROW


I don't know what `ROLE_SYSTEM_OUTLINEITEM` really does, but rows in a treegrid must contain gridcells just like rows in a grid. The only difference between treegrid rows and grid rows is that treegrid rows have a level and, if they are a parent row, have an expanded state that reflects the visibility of rows at the next level down.

**Comment by klown** [comment]
@mcking65 
I'm not an MSAA expert, and I don't know what a ROLE_SYSTEM_OUTLINEITEM is either.  [Microsoft's documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/dd373608(v=vs.85).aspx) states, "The object represents an item in an outline or tree structure.", which isn't that illuminating.  It has something to do with being inside a tree, but exactly what?

What I do know is that the mapping text has not changed since at least the [Feb 2009 working draft](https://www.w3.org/TR/2009/WD-wai-aria-implementation-20090224/#mapping_role), and likely pre-dates that draft.  That is long before my time as editor.  The primary editor then was @aleventhal, and the mapping was likely based on FireFox's implementation at that time.

@aleventhal, do you remember the rationale for this mapping?

**Comment by aleventhal** [comment]
@klown, a ROLE_SYSTEM_OUTLINE is just a tree item in MSAA. Part of the adoption strategy for ARIA was to first make widgets look similarly in MSAA to widgets on Windows. This allowed screen readers to work right away. It's very, very difficult to get screen readers to change when they already have a way of making things work. In fact, it gets very expensive.  So as a pragmatic thing we map ARIA to something they know, and ask them for tweaks when we absolutely have to.

In this case, they could already process a tree or treegrid as a ROLE_OUTLINE with ROLE_OUTLINEITEM descendants.

**Comment by aleventhal** [comment]
What we want is this option:
"ROLE_SYSTEM_ROW unless inside a treegrid, in which case ROLE_SYSTEM_OUTLINEITEM"

We absolutely don't want to break screen reader implementations and cause us to have to shift priorities and resources to something unless it adds real value.
