### ISSUE TITLE
Core AAM: Ensure UIA live region mappings are correct

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#614]
I'm seeing a bit of inconsistency with the UIA mappings for ARIA's live region roles, which I've ordered to group similarly-written mappings together:

* [log](https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#role-map-log):
   > Control Type is Group.
   > Localized Control Type is log.
   > LiveSettingProperty = Polite (1).
* [status](https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#role-map-status)
   > Control Type is Group.
   > Localized Control Type is log.
   > LiveSettingProperty = Polite (1).
* [alert](https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#role-map-alert):
   >  Text
   > The user agent should fire a system alert event.
* [marquee](https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#role-map-marquee):
   > Text
* [timer](https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#role-map-timer)
  > Expose as text string in AriaRole

Setting aside whether or not the Control Type is prefaced with "Control Type is"), I have the following questions:

1. Is it correct that alert, log, and timer lack the following?
   * Localized Control Type
   * LiveSettingProperty value
1. What's up with the timer mapping:
   * Expose _what_ as a text string in AriaRole?
   * If this live region role is really so special as to have such a unique mapping, should that be stated explicitly?

@boggydigital: Assigning to you. If the spec is as it should be, please explain. Otherwise, please create a pull request containing the corrections. As always, thanks in advance for your help! :)

**Comment by joanmarie** [comment]
@boggydigital: In order to track which issues I'm waiting on others to respond, versus those I can proceed to work on, I've created and used a "needinfo" label. When you've responded, please remove that label. Thanks!

**Comment by boggydigital** [comment]
I'm going one by one:

- role=log seems correct to me
- role=status seems correct to me in the specification. In the text above it says LCT = "log", that is just a typo, specification suggests correct value "status"
- role=alert, seems inconsistent to me - proposed change to align with log, status (https://github.com/w3c/aria/pull/624 + patch revision as I forgot to add LiveSettingProperty)
- role=marquee, seems inconsistent to me - proposed change to align with log, status, alert (https://github.com/w3c/aria/pull/625)
- role=timer doesn't make any sense to me either. Proposed consistent change (https://github.com/w3c/aria/pull/626)

Now to your specific questions:

> Is it correct that alert, log, and timer lack the following? 

I don't believe this is the correct intent. This would make it inconsistent with other implementations as well as with itself. Series of proposed changes should take care of that and all live regions should be mapped consistently now.

> What's up with the timer mapping

I have no idea what happened here. Let's assume this was just a mistake - should be fixed in the proposed change consistently with other changes.

**Comment by joanmarie** [comment]
Thanks! All pull requests merged.
