### ISSUE TITLE
Core-AAM: Confirm UIA term role mapping

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#617]
As stated in issue #455, the `term` role is not a list item, but the UIA mappings map it as if it were. We need to confirm that this mapping is correct, or fix it if it is not.

@boggydigital: Here's another one for you. Please and thank you!

**Comment by boggydigital** [comment]
This looks straightforward: https://github.com/w3c/aria/pull/628

I understand that it was mapped to ListItem control type only because of some similarity with dt element, however that doesn't sense to me here. Reading through parallel discussions I certainly agree with IA2 mapping and mapped UIA consistently.

**Comment by joanmarie** [comment]
Thanks! Merged.
