### ISSUE TITLE
Need to check roles which support aria-expanded

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria#681]
Because aria-expanded is supported on these roles:
* button
* combobox
* document
* link
* menuitem
* section
* sectionhead
* window

The full set of roles it is supported on is:
* alert
* alertdialog
* article
* banner
* cell
* columnheader
* complementary
* contentinfo
* definition
* dialog
* directory
* feed
* figure
* form
* grid
* gridcell
* group
* heading
* img
* landmark
* list
* listbox
* listitem
* log
* main
* marquee
* math
* menu
* menubar
* menuitemcheckbox
* menuitemradio
* navigation
* note
* progressbar
* radiogroup
* region
* row
* rowheader
* search
* select
* status
* tab
* table
* tabpanel
* term
* timer
* toolbar
* tooltip
* tree
* treegrid
* treeitem

Is an alertdialog really expandable? What about a progressbar? And I'm not an author, but what is the advantage of making main expandable? Let's sanity-check these.

**Comment by mcking65** [comment]
Definition of aria-expanded:

> Indicates whether the element, or another grouping element it controls, is currently expanded or collapsed.

In practice to-date, aria-expanded is applied to the controlling element, e.g., button, treeitem, menuitem, or row in a treegrid. Applying aria-expanded to a controlled grouping element is not helpful, especially since in most cases the element is not even present in the accessibility tree; it is often hidden with display:none.

The current set of roles that support aria-expanded is based on the idea that we would apply aria-expanded to the grouping element. This would really only work well if:

1. The grouping element has a visual representation that was rendered in both the expanded and collapsed states;
2. The grouping element is focusable and interactive;
3. The grouping element does not have a separate controlling element for expanding and collapsing.

It is possible to imagine such an element. Perhaps a focusable div that expands and collapses when activated. If someone were to make such a thing, the question then becomes: which of the container or grouping types of roles could describe it without violating other requirements associated with those roles?

We also need to consider whether there are roles that should support aria-expanded but do not. Checkbox does not currently support aria-expanded, but a checkbox can control visibility of a section of content.

#### Questions and principles

1. Should we avoid adding limitations that are not absolutely necessary to avoid clearly predictable AT interoperability problems?
2. Does applying a role that the ARIA taxonomy classifies as a structure to a focusable and interactive element violate any normative requirements? For example, does making a region focusable and interactive necessarily cause problems?

#### Keep case is clear for

* button
* combobox
* gridcell
* listbox
* menuitem
* row
* rowheader
* tab
* treeitem

#### Remove Case is Clear for

* alertdialog
* cell
* link
* menu
* menubar
* menuitemcheckbox
* menuitemradio
* tooltip

#### Add case is clear for

* Checkbox

#### Muddy waters surround

* alert
* article
* banner
* columnheader
* complementary
* contentinfo
* definition
* dialog
* directory
* document
* feed
* figure
* form
* grid
* group
* heading
* img
* list
* listitem
* log
* main
* marquee
* math
* navigation
* note
* progressbar
* radiogroup
* region
* search
* status
* table
* tabpanel
* term
* timer
* toolbar
* tree
* treegrid

**Comment by jnurthen** [comment]
I agree with all the removals except for link. A link can certainly control an expandable region.

**Comment by jspurlin** [comment]
@mcking65 I agree for the most part but there's a few other roles that come to mind that don't seem to be addressed yet: option, textbox, and searchbox.

Those are some other roles that have aria-haspopup but does not support aria-expanded (there might be more, but these are the one's I've run in to most recently). For the textbox/serachbox example, if it displays results I've seen examples state to make the input a comboBox. The issue with that is you must use a listbox with a comboBox (for the "menu" scenario), and a listbox must contain option(s), but options currently do not allow for aria-expanded...

**Comment by mcking65** [comment]
I'll make a separate PR to remove aria-expanded inherritance into menuitemradio and menuitemcheckbox; those need to be addressed before closing this issue.

**Comment by zcorpan** [comment]
I found this when researching for writing a new section in aria-practices for Controlling Widget States.

Here are the issues me and @spectranaut found:

* `tabpanel` - what is the advantage of using `aria-expanded` when `aria-selected` already indicates which tabs are selected?
* The spec is inconsistent about whether `aria-expanded` should go on `tabpanel`, `tablist`, or `tab`.

> For a multi-selectable tablist, authors SHOULD ensure each visible tabpanel has its aria-expanded attribute set to true, and that the remaining hidden tabpanel elements have their aria-expanded attributes set to false.

https://w3c.github.io/aria/#tab

> For a multi-selectable tablist, authors SHOULD ensure each visible tabpanel has its aria-expanded attribute set to true, and that the remaining hidden tabpanel elements have their aria-expanded attributes set to false.

https://w3c.github.io/aria/#tablist

...but `aria-expanded` is a supported state on `tab`, not `tabpanel` or `tablist`

**Comment by jnurthen** [comment]
@zcorpan Can you please open a new issue for this. This issue has already been merged.

**Comment by zcorpan** [comment]
done https://github.com/w3c/aria/issues/1032
