### ISSUE TITLE
Aria 1.1 external file : XSD, RDF/XML should be put on github

### ISSUE THREAD

**Issue by innovimax** [w3c/aria#685]
I don't find the external file for Aria 1.1
I see that there is an issue for Aria 1.2 #672 to remove them altogether, but in the meantime they are needed for Aria 1.1 to progress to REC

**Comment by michael-n-cooper** [comment]
ARIA 1.1 has already progressed to Rec.

It wouldn't make sense to put these files in GitHub because they are simply generated from the ARIA source. For 1.0 there was an XSLT-based generator, which may need updating to work with the 1.1 structure. It makes sense for the generator to be in GitHub, so I will do that and update it when I get a chance, and then regenerate the schemata to reflect the 1.1 features.

**Comment by innovimax** [comment]
may be this could have been avoided https://twitter.com/innovimax/status/942083261492350976

**Comment by jnurthen** [comment]
@michael-n-cooper Can you please update - I think this is overcome by events.

**Comment by jnurthen** [comment]
Based on #672 to remove these I am closing this issue
