### ISSUE TITLE
Need 'aria-selected' and 'aria-controls' as 'Required States and Properties' when using role 'tab'

### ISSUE THREAD

**Issue by iamrafan** [w3c/aria#690]

**Comment by jnurthen** [comment]
Tab states the following:
"In either case, authors SHOULD ensure that a selected tab has its aria-selected attribute set to true, that inactive tab elements have their aria-selected attribute set to false, and that the currently selected tab provides a visual indication that it is selected. In the absence of an aria-selected attribute on the current tab, user agents SHOULD indicate to assistive technologies through the platform accessibility API that the currently focused tab is selected."

hence it is stating that aira-seleced is not required

I don't want to make aria-controls required due to its limited utility
