### ISSUE TITLE
for attribute of label with matching ID attribute of aria widget

### ISSUE THREAD

**Issue by devarshipant** [w3c/aria#707]
The label's **for attribute** matches with **ID attribute** of the ARIA widget (role = listbox), which is not an `input `element, but a `div`. Is this acceptable from a standards perspective?

Example:

```
<label id="listbox_option" for="listbox_option_list">Search for Cases by</label>

<div tabindex="0" class="ui selection dropdown" id="listbox_option_list" 
role="listbox" aria-expanded="false" aria-activedescendant="listbox_option_0" ...
```

**Comment by stevefaulkner** [comment]
>
> The label's *for attribute* matches with *ID attribute* of the ARIA
> widget (role = listbox), which is not an inputelement, but a div. Is this
> acceptable from a standards perspective?


No as it does not work, label elements can only be associated with labelable
elements <https://w3c.github.io/html/sec-forms.html#labelable-element>
using for/id

--

Regards

SteveF
Current Standards Work @W3C
<http://www.paciellogroup.com/blog/2015/03/current-standards-work-at-w3c/>

**Comment by devarshipant** [comment]
> No as it does not work, label elements can only be associated with labelable
elements <https://w3c.github.io/html/sec-forms.html#labelable-element>
using for/id

thanks @stevefaulkner. However, it works with JAWS 18 / NVDA with IE 11 / Edge / Firefox (57)  [Win 10 / 64 bit].

Just curious--is there any reason why a `div ` that has been transformed into a form control (using a role = listbox etc.) not considered a labelable element?

**Comment by stevefaulkner** [comment]
> Just curious--is there any reason why a div that has been transformed into a form control (using a role = listbox etc.) not considered a labelable element?

because what is/is not a labelable element is defined in HTML not ARIA. Indeed [I myself have raised the issue](https://lists.w3.org/Archives/Public/public-webapps/2015AprJun/0561.html) of being able to associate a label with an element that has an ARIA control role, but it was rejected by some implementers and is not defined for implementations in any specification.

Interestingly using the [test case](https://s.codepen.io/stevef/debug/gebOOQ) It does actually work in IE/Edge, but not in Firefox/chrome. That is in IE/Edge the accessible name for the listbox is provided by the label. What you experience with SR's and it appearing to work in Firefox/chrome is the SR's heuristics, in the absence of an accessible being exposed in the accessibility tree by the browser SR's in some circumstances will announce nearby text as the control label.

**Comment by accdc** [comment]
Hi,

The following response from a different thread may shed some light on this topic as well regarding native host semantics such as native active elements and how property assignments are made as opposed to simulated widget constructs.

https://github.com/w3c/accname/issues/2#issuecomment-371904337

**Comment by devarshipant** [comment]
@stevefaulkner -- perhaps there is enough traction within IE / Edge to revisit part 1 of your [post](https://lists.w3.org/Archives/Public/public-webapps/2015AprJun/0561.html) where you stated:

> 1. When a role is used that matches the default implicit semantics of
labelable HTML elements [1] use of the label element will result in the
same behaviour as the native element and a `<label>`.

> ```
> <span role="checkbox" id="customcheck"></span>
> <label for="customcheck">i like this idea</label>
> ```

Besides exposing the label as the accessible name of checkbox, it would also allow users to click on the label to check / uncheck the control (larger clickable area). 

We don't need to extend ARIA all at once. Starting piecemeal and taking bits that won't break, for example, allowing web devs to create a native html control out of a `<div>` with an ARIA role, might be a way forward.

**Comment by mcking65** [comment]
I wonder if implementers would be willing to go in the other direction ... support clicking elements referenced by aria-labelledby in the same way that support clicking html label elements with a for attrib? That is something we could specify in the ARIA spec.

**Comment by stes-acc** [comment]
If so, it would be also allow for quick association check without any AT or API reading tool. Just click on label-like stuff. Can come in handy.


  *   Stefan

**Comment by carmacleod** [comment]
Except that it kinda goes against this statement that has been in effect since the [ARIA 1.0 spec](https://www.w3.org/TR/wai-aria-1.0/introduction#ua-support):
> The WAI-ARIA specification neither requires nor forbids user agents from enhancing native presentation and interaction behaviors on the basis of WAI-ARIA markup.

So we can't "require" that user agents enhance interaction for aria-labelledby elements; unless we change one of the original User Agent Support statements of ARIA.

**Comment by accdc** [comment]
That’s the same argument against that I was given by Microsoft and Apple last time I brought this up in 2014.

**Comment by devarshipant** [comment]
Circling back to the original post -- the idea is to extend the ARIA feature set to eventually support functional properties like programmatic association, focus, and rendering of the converted element. 

Please note, I am not a developer, so pardon my lack of dev speak. 

Possible ideas to be considered in a future version:

1. Landmark roles provide keyboard support for all users, not just screen reader users.

2. Menu structures can be created with less code where the menu / menuitem roles 'carry' more to the interface.

3. Programmatic association between ARIA form controls and labels is possible using HTML association methods.

4. Using a role (listbox, combobox, tablist) should render or 'create' the element without relying on html structures.

**Comment by accdc** [comment]
If I understand correctly, you are saying that functionality should be automatically applied when widget roles are added to markup. Is this correct?

 

Personally I don’t think this will ever happen, because it goes completely against the ARIA spec which states that the use of ARIA will not cause any functional change to occur within the browser. This was an important addition back when we spoke of it in 2014 because it is impossible to predict how web developers will create these structures, and for any automatic behavior to occur it would require specific and reliably constructed parent child relationships that are impossible for browsers to get right consistently when devs often use incorrect markup or insert other things that are not valid within those structures.

 

Another issue brought up back then was that of event processing conflicts. E.G What would happen if you had a button that included aria-haspopup to indicate that it opened a popup menu, and this button was placed within a container element referenced by a form control via aria-labelledby? The browser may then hijack the onClick when the button was pressed to force focus into the form field and make it impossible to use the menu from the keyboard. Also if the browser hijacks processing events like arrow key presses in the case of Listboxes, what happens to similar event handlers added for different purposes by developers on the same elements? Does one cause the others to disappear? Do they all get fired at the same time no matter what they do? Or does something else happen instead?

 

There are too many situations like this on the web, which is why such automatic hijacking of functional events by browsers may cause a lot more headaches than not if implemented.

**Comment by carmacleod** [comment]
@devarshipant To your first point...
> 1.	Landmark roles provide keyboard support for all users, not just screen reader users.

...please feel free to try to encourage the browsers to implement this. I have been trying for years... ;)
- [Firefox feature request](https://bugzilla.mozilla.org/show_bug.cgi?id=670928)
- [Chrome feature request](https://bugs.chromium.org/p/chromium/issues/detail?id=704698)
- [Safari feature request](https://bugs.webkit.org/show_bug.cgi?id=172817)
- [Edge feature request](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/19436788-landmark-navigation)

**Comment by devarshipant** [comment]
@accdc: 
> If I understand correctly, you are saying that functionality should be automatically applied when widget roles are added to markup. Is this correct?

Yes.

> There are too many situations like this on the web, which is why such automatic hijacking of functional events by browsers may cause a lot more headaches than not if implemented.

You are correct. 

Question--what causes the [test case reported earlier](https://s.codepen.io/stevef/debug/gebOOQ) to expose accessible name in the accessibility tree and also provide click area only in **Edge** but not in Chrome and Firefox? I am assuming the DOM to [platform accessibility API ](https://w3c.github.io/core-aam/#accessible-names-and-descriptions) contract is not fulfilled in chrome and firefox.

**Comment by devarshipant** [comment]
@carmacleod --

> ...please feel free to try to encourage the browsers to implement this. I have been trying for years... ;)

Interesting ideas were generated in your feature requests. [Your suggestion to repurpose ](https://bugzilla.mozilla.org/show_bug.cgi?id=670928)and assign F6 key to rotate through landmarks (and include headings?) sounds practical. The way I understand screen readers, landmarks are navigable in virtual cursor mode (browse mode), so to enable non-visual keyboard only users access to landmarks, the browser could look at the first semantic element with accessible name in the `<div>` with landmark, for example, in `<div role = "navigation">....<h3...>Navigation Heading Text</h3>`,  the browser creates traversal tree (list) with Navigation Heading Text as one of the nodes.

**Comment by carmacleod** [comment]
Thanks for reading through all of that @devarshipant - that was a lot of reading.  :)
I think that if I could rewrite those comments today, I would completely separate landmark navigation from heading navigation:
- Landmarks are a convenient way to move around a page. There should only be a relatively small number of landmarks (rule of thumb is to have no more than 6 or so, if possible).
- Headings are for defining sections that go in an outline of the _information architecture_ of the page. There can be lots and lots of headings.

So I think there should be one key combination for landmark navigation (perhaps F6 and shift+F6), and a different key combination for heading navigation (haven't looked into what might work for that... perhaps ctrl+backtick and ctrl+shift+backtick ... not sure).

Similarly, for the GUI feature (user types in list in side panel or dialog or whatever), I would put the page's landmarks in a completely separate list from the page's headings.

**Comment by jnurthen** [comment]
I'm not sure what issue this is covering - it seems to have morphed between a request for label to label a form element to a request to have browsers handle landmark navigation. Neither of these are ARIA spec issues as far as I can tell.

If there is an issue for the ARIA spec please open a new issue as this one is too confused.

**Comment by carmacleod** [comment]
Quite right, @jnurthen - my bad.
I tend to segue into a landmarks discussion whenever they are mentioned.  ;)
