### ISSUE TITLE
need role for label

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria#876]
per [plans for role parity](https://github.com/w3c/aria/wiki/Plans-regarding-role-parity#specific-role) need a role for equivalent to [`<label>`](https://www.w3.org/TR/html52/sec-forms.html#the-label-element) in HTML

**Comment by mbrookes** [comment]
I looked at the associated PR that closes this issue,  but I don't see HTML list items included in the list of html elements this applies to.

How does one provide a label that is part of the list structure, but distinct from the list items? Since only `<li>` is a valid child of list, the logical solution would be: `<li role="label">List section label</li>` (following the `<li role="separator" />` syntax), for example:

```html
<ul aria-label="shopping list">
  <li role="label">Bakery</li>
  <li>Bread</li>
  <li>Croissants</li>
  <li role="label">Fruit</li>
  <li>Apples</li>
  <li>Grapes</li>
  <li>Bananas</li>
  [...]
</ul>
```

Here is a practical example of where this would be useful: https://material-ui.com/demos/lists/#pinned-subheader-list

If there is already a semantically correct and ARIA compliant / accessible way to achieve this, then apologies, and please let me know.

**Comment by jnurthen** [comment]
@mbrookes looks like a group in a list to me http://w3c.github.io/aria/#list

**Comment by mbrookes** [comment]
@jnurthen Thanks, but I still don't see how one provides a syntactically correct visible label, whether items are grouped or not. Is there a practical example you could point me to? Thanks!

**Comment by jongund** [comment]
@mbrookes The example you providing is related to grouping labels, so there needs to be a grouping role:

```
<ul aria-label="shopping list">
  <li>Bakery
       <ul aria-label="Bakery">
          <li>Bread</li>
         <li>Croissants</li> 
        </ul>
  </li>
  <li>Fruit
      <ul aria-label="Fruit>
         <li>Apples</li>
         <li>Grapes</li>
         <li>Bananas</li>
      </ul>
  </li>
  [...]
</ul>
```

**Comment by mcking65** [comment]
> @mbrookes The example you providing is related to grouping labels, so there needs to be a grouping role:
> 
> ```
> <ul aria-label="shopping list">
>   <li>Bakery
>     <ul aria-label="Bakery">
>       <li>Bread</li>
>       <li>Croissants</li> 
>     </ul>
>   </li>
>   <li>Fruit
>      <ul aria-label="Fruit>
>        <li>Apples</li>
>        <li>Grapes</li>
>        <li>Bananas</li>
>      </ul>
>   </li>
>   [...]
> </ul>
> ```

@mbrookes, @jongund, while technically correct, I'm having a hard time picturing how it would help me as a user. If I'm reading the page sequentially, I'm going to hear the labeling item twice, first when I read the fruits list item, then again when I start reading the nested list of fruits. That would get pretty annoying, especially if the list items are more than a single word.

In circumstances where the user might jump from nested list to nested list, there is a possibility it could be helpful, but it's not clear to me it be worth the trade-off, especially since it would be almost as easy to jump from parent list item to parent list item.

At any rate, for a first go at the label role, this use case would not fit in our current scope of simple parity with HTML because the HTML label element does not support this type of useage.

**Comment by mbrookes** [comment]
So, am I understanding correctly that there is no syntactically correct way to label groups in lists in a way that that works both visually and with screen readers?

**Comment by jongund** [comment]
@mbrookes grouping labels need some type of semantic structure to indicate the grouping relationship.  It seems like from your code example you want more of a heading than a group label (e.g. here is the next section of related to bakery and another on fruit, so that code would be:

<h2>Shopping list</h2>
<h3>Bakery</h3>
<ul>
   <li>Bread</li>
   <li>Croissants</li> 
</ul>
<h3>Fruit</h3>
<ul>
    <li>Apples</li>
    <li>Grapes</li>
    <li>Bananas</li>
</ul>
[...]

**Comment by mbrookes** [comment]
Please could you wrap the code sample in ```s. Thanks. :)

**Comment by jongund** [comment]
@mbrookes sorry, I fixed the sample

**Comment by mbrookes** [comment]
Thanks. In this example the list isn't a list though. It's two lists. 🤷‍♂️
