### ISSUE TITLE
need role for time element

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria#878]
per [plans for role parity](https://github.com/w3c/aria/wiki/Plans-regarding-role-parity#specific-role) need a role for equivalent to [`<time>`](https://www.w3.org/TR/html52/textlevel-semantics.html#the-time-element) in HTML

**Comment by melanierichards** [comment]
On the 7 Feb, 2019 call I mentioned I'd add examples of [HTML expectations for the time element](https://www.w3.org/TR/html52/textlevel-semantics.html#the-time-element) so we can work out the open questions on the PR. They are:

a) Author provides a machine-readable `datetime` content attribute on the `<time>` element, and is then free to provide human-readable (for example) child phrasing contents of the element:

```
<time datetime="2011-02-07">
  <span>Today's conference call</span>
</time>
```

b) Author does not use the `datetime` content attribute, and the `<time>` element must not have element descendants, as the text contents themselves are meant to be used for the human-readable format:

```
<time>2011-02-07</time>
```

**Comment by melanierichards** [comment]
Questions we discussed:

* Added an author should to match the content expectations of HTML. Should this really be a SHOULD, since that'll generate implications for compliance checkers, or should we change to a gentler suggestion? I don't believe we got formal resolution on this but we can review the next call this comes up.
* Didn't mark this as "children presentational" but perhaps it should be, given HTML expectations: "A `time` element that does not have a `datetime` content attribute must not have any element descendants." I don't think we need to do this, given that we are adding the `aria-datetime` attribute and in my opinion it would be potentially unnecessarily complex to have different presentational rules with or without the attribute.
* For the role parity exercise, do we need something like `aria-datetime`? We determined that we do; #898

**Comment by melanierichards** [comment]
@jnurthen is there a preferred way to notify the group/chairs that PR changes are in and ready to review at an upcoming call? (This is also me notifying that #895 has been updated!)

Changes made, for call reference:

* Added note about potential future `aria-datetime` property
* Added valid date- and time- strings inline and removed normative reference to the HTML spec for this purpose; I added one example per category. The HTML spec is much more exhaustive, open to adding all of them if requested, but hopefully this a good set to get the point across
* Documented the HTML expectations for `<time>` element authoring, in [a comment earlier in this issue thread](https://github.com/w3c/aria/issues/878#issuecomment-461570281). This is for reference as to whether children should be presentational or not.
* Also removed name from contents

**Comment by pkra** [comment]
@melanierichards I think adding the label "agenda" to the issue is enough.

**Comment by jnurthen** [comment]
Adding Agenda can work but an email is also good.... We review everything with Agenda on it during out planning meeting on Tuesdays so if it has Agenda before then it will be considered. Apologies for not putting this on earlier though.

**Comment by melanierichards** [comment]
@jnurthen you didn't miss it, it just took me forever to cycle back and make the changes 😅 Email to chairs or to the group?

**Comment by jnurthen** [comment]
@melanierichards up to you... We will see it either way. Also when the agenda goes out if something isn't on it which you think should be please let me know.
