### ISSUE TITLE
The ARIA 1.1 Combobox design pattern endorses unlabelled form fields as normative spec.

### ISSUE THREAD

**Issue by accdc** [w3c/aria#893]
Within the ARIA 1.1 Combobox design pattern, the following markup is specified as the proper syntax for the new 1.1 combobox structure.

```
<div aria-label="Tag" role="combobox" aria-expanded="true" aria-owns="owned_listbox" aria-haspopup="listbox"> 
    <input type="text" aria-autocomplete="list" aria-controls="owned_listbox" aria-activedescendant="selected_option">
</div>
<ul role="listbox" id="owned_listbox"> 
    <li role="option">Zebra</li> 
    <li role="option" id="selected_option">Zoom</li>
</ul>
```

Specifically, the following:

```
    <input type="text" aria-autocomplete="list" aria-controls="owned_listbox" aria-activedescendant="selected_option">
```

This is going to lead to major accessibility issues across devices since the combobox role is not a substitute for a labelling mechanism according to the AccName spec.

**Comment by carmacleod** [comment]
> the combobox role is not a substitute for a labelling mechanism according to the AccName spec.

Would it work if we add an item to the beginning of the list in AccName step 2E to say something like:
- If the embedded control has role textbox, and it is a descendant of an element with role combobox, then compute the text alternative for the combobox beginning with step 2, and set the result to that text alternative. Append the value of the textbox control to the result, with a space. Return the result.

@joanmarie Is this close? You are so good with AccName words! :smile:

**Comment by carmacleod** [comment]
Here are [3 more combobox test cases](https://carmacleod.github.io/playground/combo-test.html) that I would like to ensure would work with any accname changes that we make. Note that none of these have aria-autocomplete.
- Combo 1 is basically the same as @accdc's example, above, except with a visible label
- Combo 2 is the same as Combo 1 except read-only
- Combo 3 uses a span for the textbox, tabindex="0" on the combobox div, and it "pops up" a dialog instead of a listbox

One problem that is noticeable is that JAWS and NVDA don't even recognize Combo 1 and Combo 2 as a combobox, let alone labelling them correctly. The same problem exists with the APG ARIA 1.1 combobox examples, but it is not as noticeable because those examples all have aria-autocomplete and they are spoken as "Edit, has autocomplete", so the user might miss that there's no mention of "combobox".

**Comment by stes-acc** [comment]
> One problem that is noticeable is that JAWS and NVDA don't even recognize Combo 1 and Combo 2 as comboboxes....

This is something to file in [github of VFO-standards-support](https://github.com/FreedomScientific/VFO-standards-support/issues?utf8=%E2%9C%93&q=combo).

**Comment by carmacleod** [comment]
Good point @stes-acc. Also [NVDA Github Issues](https://github.com/nvaccess/nvda/issues).
However I think I will wait until after the 1.1 combobox pattern is discussed at the F2F.

**Comment by carmacleod** [comment]
Actually, there may already be an open issue for this against JAWS:
- https://github.com/FreedomScientific/VFO-standards-support/issues/167

There are open JAWS issues for the labelling problem to keep in mind for the discussion, because putting the label on the input results in unlabelled comboboxes in the JAWS Form Fields Dialog:
- https://github.com/FreedomScientific/VFO-standards-support/issues/77
- https://github.com/FreedomScientific/VFO-standards-support/issues/171

**Comment by jnurthen** [comment]
related https://github.com/w3c/aria/issues/1046

**Comment by zcorpan** [comment]
#1051 is merged.
