### ISSUE TITLE
Should there be an emoji role?

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria#919]
Emoji are very different to text and also very different from images
Take the 💩 emoji 
Knowing that this is the "pile of poo emoji" is really important. If this just read as text "pile of poo" this does not have the same meaning. I have heard suggested to use img but "pile of poo image" is just gross.

**Comment by scottaohara** [comment]
repost from another discussion about this:

Consider a situation where ❤️ (an emoji) is used a valid CSS class (a very specific situation... but still).

Teseting [this codepen example](https://codepen.io/scottohara/pen/jJQZoe) with NVDA and VoiceOver, the class is announced as "red heart".  And that makes sense, because that's what it is... but `class="red-heart"`, `class="red heart"` and `class="❤️"` won't all behave as expected.

**Comment by pkra** [comment]
To me, it seems the more general problem is one of verbosity. 

Emojis (and other Unicode symbols) are just as likely to be used as direct replacements for words. In that case it seems very noisy to, e.g., "I'm on the train-emoji looking or a seat-emoji near the exit-emoji" seems not-ideal.  The same is true for arrows, dingbats, chess pieces and lots of other Unicode which are not considered "emoji".

**Comment by LJWatson** [comment]
I don't think verbosity is really an issue, and if it is, it's one that can easily be solved at the screen reader level along with other forms of verbosity.

**Comment by pkra** [comment]
> I don't think verbosity is really an issue, and if it is, it's one that can easily be solved at the screen reader level along with other forms of verbosity.

Sorry for mixing two topics. I do frequently find myself in a situation where I wished for a way to indicate that more verbosity is required; this got the better of me.

Still, I would worry that a role=emoji would serve poorly in cases of Unicode points that are neither considered emoji nor textual.

**Comment by jnurthen** [comment]
> Still, I would worry that a role=emoji would serve poorly in cases of Unicode points that are neither considered emoji nor textual.

Agree - this idea isn't fully developed. Would certainly need to look at this.

**Comment by LJWatson** [comment]
I realised today that Skype prefixes emoji with the word "Emoticon" - at least Jaws announces it as such. I say "realised" because although I've been using Skype chat for many years, I obviously tune out that piece of information because (to me at least) it's redundant. It doesn't change the meaning of what's on-screen.

**Comment by AmeliaBR** [comment]
Thinking about how this would work in practice:

Would browsers be expected to automatically wrap any emoji characters in this role? And then, authors could use a role on an img element to indicate that it is a direct replacement for the emoji character. Many apps use images instead of fonts to serve their custom emoji designs, so that is a valid use case.

But it is most useful if regular emojis are exposed in the same way, and that would be rather unique as far as the relationship between the DOM and accessibility trees.

If the browsers did expose the emoji-ness of text characters automatically, it could also help distinguish between characters that can be used either with full-colour [“emoji presentation”](https://unicode.org/emoji/charts/emoji-variants.html) or more simplified “text presentation”.

**Comment by sinabahram** [comment]
Sorry, but I don’t understand why this role would be helpful. How would AT behave differently with this role?

 

Also, for definitions, I think of emoticons as textual representations e.g. a semicolon followed by a right paren for a smiley VS emoji as the actual Unicode representations that exist as a single character stop for cursor traversal.

**Comment by LJWatson** [comment]
The more I think about this, the more I agree with Sina.

If I hear "purple heart" in the content I'm reading, it doesn't matter if it's the actual words or the 💜 emoji. As screen reader consumers we've been using emoji in numerous applications without being told these single character entities were emoji.

Do we have an actual problem to solve here? Any user research that indicates emoji cause confusion because they're not identified as such?

**Comment by LJWatson** [comment]
Some other thoughts...

If the unicode emoji characters mapped to the emoji role, what would happen for emoji converted into SVG? Also what about emoji as [SVG favicons](https://twitter.com/LeaVerou/status/1241619866475474946)?

What would the expected behaviour be if an emoji was used as the content of another element like a button? Would we suppress the emoji role to let the parent element take precedence - "Eye roll button" instead of "Eye roll emoji button" or such?

Then as Sina points out, there is a difference between an ASCII art emoticon and a Unicode emoji, but it's an esoteric difference, not one that's likely to be meaningful for most consumers of content. As I mentioned above Skype already blurs the two by calling both emoticons and emoji "Emoticon".

**Comment by jnurthen** [comment]
Seeing as the 2 screen reader users on this thread see no point in it am closing.
