### ISSUE TITLE
Browser support for element/attribute reflection?

### ISSUE THREAD

**Issue by LJWatson** [w3c/aria#957]
What is the state of browser support for element/attribute reflection?

**Comment by alice** [comment]
AFAIK Safari/WebKit has shipped attribute reflection, but not element reflection. Blink has attribute reflection behind a flag.

**Comment by cookiecrook** [comment]
Related #834 and #920

**Comment by carmacleod** [comment]
I needed to test attribute reflection in order to submit a [PR for the "Button IDL" example in the APG]( https://github.com/w3c/aria-practices/pull/1161#issuecomment-527296049).

So here's an update:
Chrome: Enable chrome://flags/#enable-experimental-web-platform-features
(note: don't need to use Chrome Canary - just need to enable flag)

Edge: Use Edge Beta, Dev or Canary and enable edge://flags/#enable-experimental-web-platform-features

Firefox: Not supported yet, not even in beta with accessibility.AOM.enabled=true on the about:config page

Safari: Reflection works in latest Safari. Did not even need to enable Accessibility Object Model under Develop > Experimental Features.
